namespace GFTools.Common.Protocol.CommandIDs;

public static class WorldServerCommands {
    // Client <-> WorldServer
    public enum CW_Commands : ushort {
        CW_ClientTextOutput = 39,
        CW_ClientUpdateFamilyMember = 49,
        CW_ClientTextOutputIndex = 45,
        CW_ClientAskFamilyTransform = 79,
        CW_ClientFamilyInvitation = 70,
        CW_ClientRepeatedLogin = 52,
        CW_ClientItemMallList = 60,
        CW_ServerChangeWorldAck = 0,
        CW_ServerRemoveFriend = 1,
        CW_ServerItemMallReqBuyItem = 2,
        CW_ServerItemMallListQuery = 3,
        CW_ServerCaptchaReturn = 4,
        CW_ServerHello = 5,
        CW_ServerReceiveTicket = 6,
        CW_ServerKeepAlive = 7,
        CW_ServerLookingForMember = 8,
        CW_ServerLoginCharacter = 9,
        CW_ServerCreateCharacterName = 10,
        CW_ServerItemMallPointInfo = 11,
        CW_ServerCreateCharacterData = 12,
        CW_ServerRemoveCharacter = 13,
        CW_ServerCancelCreateCharacterReq = 14,
        CW_ServerFamilyOp = 15,
        CW_ServerQueryFamilyInfo = 16,
        CW_ServerLookingForGroup = 17,
        CW_ServerAddFriend = 18,
        CW_ServerQueryFriendInfo = 19,
        CW_ServerIllPluginInfo = 20,
        CW_ServerFriendInvitation = 21,
        CW_ServerChangeWorld = 22,
        CW_ServerItemMallAnythingReceivable = 23,
        CW_ServerItemMallReceivableList = 24,
        CW_ServerItemMallReceivableQuery = 25,
        CW_ServerItemMallReceieveAttempt = 26,
        CW_ServerQueryFamilyRecruitList = 27,
        CW_ServerQueryFamilyRecruitJoin = 28,
        CW_ServerCharPassword = 29,
        CW_ServerUpdateWorldServers = 30,
        CW_ServerQueryMail = 31,
        CW_ServerFortuneBagItemQuery = 32,
        CW_ServerFamilyTransformInvite = 33,
        CW_ServerFamilyTransformAgree = 34,
        CW_ServerFamilyTreeOperation = 35,
        CW_ServerQueryFunctionSwitch = 36,
        CW_ClientReceiveTicketToWorld = 37,
        CW_ClientHello = 38,
        CW_ClientReceiveTicketToZoneServer = 40,
        CW_ClientGetCharacters = 41,
        CW_ClientVerifyCharacterName = 42,
        CW_ClientResetTime = 43,
        CW_ClientCancelCreateCharacterResp = 44,
        CW_ClientChannelMsg = 46,
        CW_ClientLookingForMemberResult = 47,
        CW_ClientXTrapCSStep1To2 = 48,
        CW_ClientUpdateFriendMember = 50,
        CW_ClientFriendInvitation = 51,
        CW_ClientException = 53,
        CW_ClientItemMallAnythingReceivable = 54,
        CW_ClientItemMallReceivableQuery = 55,
        CW_ClientItemMallReceieveAttempt = 56,
        CW_ClientTicketInvalid = 57,
        CW_ClientUpdatePrestigeData = 58,
        CW_ClientUpdateBlackList = 59,
        CW_ClientItemMallReqBuyItem = 61,
        CW_ClientItemMallPointInfo = 62,
        CW_ClientGetWorldServers = 63,
        CW_ClientFamilyAchievementUpdate = 64,
        CW_ClientCaptcha = 65,
        CW_ClientCrossZone = 66,
        CW_ClientQueryFamilyRecruitList = 67,
        CW_ClientTell = 68,
        CW_ClientFamilyOpException = 69,
        CW_ClientFamilyQuit = 71,
        CW_ClientQueryFamilyInfo = 72,
        CW_ClientFamilySchedule = 73,
        CW_ClientCharPassword = 74,
        CW_ClientApexBufferTransfer = 75,
        CW_ClientMailList = 76,
        CW_ClientMailRead = 77,
        CW_ClientFortuneBagItem = 78,
        CW_ClientGetMotionEndTime = 80,
        CW_ClientFunctionSwitch = 81,
        CW_ServerTextCommand = 0
    }

    public const ushort DBA_AgentDBACommand = 20;
    public const ushort G_ServerCharacterLogin = 16;
    public const ushort G_ServerCharacterLogout = 17;
    public const ushort ZMis_MissionServerAddFamilyMessage = 54;
    public const ushort ZMis_MissionServerCheckFamilyInvite = 8;
    public const ushort ZW_ZoneServerTextCommand = 24;
    public const ushort G_ServerAccountLogout = 1;
    public const ushort ZW_ZoneServerUpdateFortuneBag = 27;
    public const ushort ZW_ZoneServerUpdateLottery = 29;
    public const ushort G_ServerSaveHealthTime = 21;
    public const ushort ZW_ZoneServerReportID = 16;
    public const ushort T_ServerGetTicket = 0;
    public const ushort G_ServerGetPointInfo = 4;
    public const ushort ZW_ZoneServerItemMallReceieveAttempt = 25;
    public const ushort ZMis_MissionServerItemMallMailCheck = 53;
    public const ushort ZW_ZoneServerGetCloneItemID = 26;
    public const ushort G_ServerReqBuyItem = 5;
    public const ushort T_ServerUseTicket = 1;
    public const ushort T_ClientGetTicket = 2;
    public const ushort T_ClientUseTicket = 3;
    public const ushort T_ServerCheckPin = 4;
    public const ushort T_ClientCheckPin = 5;
    public const ushort G_ServerBillingLogin = 2;
    public const ushort G_ServerAccountLogin = 0;
    public const ushort G_ServerClientTypeReport = 3;
    public const ushort G_ClientAccountLogin = 6;
    public const ushort G_ClientAccountLogout = 7;
    public const ushort G_ClientKickUser = 8;
    public const ushort G_ClientServerTypeReport = 9;
    public const ushort G_ClientSetWorldStates = 10;
    public const ushort G_ClientBillingLogin = 11;
    public const ushort G_ClientGetPointInfo = 12;
    public const ushort G_ClientReqBuyItem = 13;
    public const ushort G_ServerTextCommand = 14;
    public const ushort G_ClientTextCommand = 15;
    public const ushort G_ServerExchangePinItem = 18;
    public const ushort G_ServerExchangePinUpdateState = 19;
    public const ushort G_ClientExchangePinItemResult = 20;
    public const ushort G_ClientUpdateHealthTime = 22;
    public const ushort ZMis_MissionServerItemMallMailSend = 52;
    public const ushort ZW_WorldServerIDReport = 0;
    public const ushort ZW_WorldServerTell = 1;
    public const ushort ZW_WorldServerAllUsers = 2;
    public const ushort ZW_WorldServerNotifyEntry = 3;
    public const ushort ZW_WorldServerCharacterArrived = 4;
    public const ushort ZW_WorldServerResetTime = 5;
    public const ushort ZW_WorldServerReturnToCharacterList = 6;
    public const ushort ZW_WorldServerTeamLeavedNotify = 7;
    public const ushort ZW_WorldServerChannelMsg = 8;
    public const ushort ZW_WorldServerFamilyCreation = 9;
    public const ushort ZW_WorldServerLogout = 10;
    public const ushort ZW_WorldServerTextCommand = 11;
    public const ushort ZW_WorldServerItemMallReceieveAttempt = 12;
    public const ushort ZW_WorldServerGetCloneItemID = 13;
    public const ushort ZW_WorldServerFBMsgUpdate = 14;
    public const ushort ZW_WorldServerTextExCmd = 15;
    public const ushort ZW_ZoneServerDestShutdown = 17;
    public const ushort ZW_ZoneServerCharacterArrive = 18;
    public const ushort ZW_ZoneServerCharacterArrivedDest = 19;
    public const ushort ZW_ZoneServerChannelMsg = 20;
    public const ushort ZW_ZoneServerChangeFamily = 21;
    public const ushort ZW_ZoneServerNewFamily = 22;
    public const ushort ZW_ZoneServerRemoveFamily = 23;
    public const ushort ZW_ZoneServerFamilyUseSpell = 28;
    public const ushort ZW_ZoneServerTextExCmd = 30;
    public const ushort ZW_ZoneServerGMToolGetInfo = 31;
    public const ushort MW_WorldServerTell = 0;
    public const ushort MW_WorldServerItemMallMailSendResult = 1;
    public const ushort MW_WorldServerItemMallMailCheckOK = 2;
    public const ushort MW_WorldServerCrossZone = 3;
    public const ushort MW_WorldServerUpdateBlackList = 4;
    public const ushort MW_WorldServerUpdatePrestigeData = 5;
    public const ushort MW_WorldServerUpdateFriendMember = 6;
    public const ushort MW_WorldServerCheckFamilyInvite = 7;
    public const ushort MW_WorldServerFBMsgUpdate = 9;
    public const ushort MW_WorldServerTextExCmd = 10;
    public const ushort MW_WorldServerTextExCmdRemoteWorld = 11;
    public const ushort MW_WorldServerTextExCmdRemoteZone = 12;
    public const ushort MW_WorldServerFunctionSwitchUpdate = 13;
    public const ushort MW_MissionServerTextExCmd = 14;
    public const ushort MW_MissionServerTextExCmdRemoteWorld = 15;
    public const ushort MW_MissionServerTextExCmdRemoteZone = 16;
    public const ushort ZM_ZoneServerUpdatePKList = 17;
    public const ushort ZMis_MissionServerUpdatePKList = 18;
    public const ushort MW_WorldTextCommand = 19;
    public const ushort DBA_ClientContainer = 21;
    public const ushort DBA_ClientEnchant = 22;
    public const ushort DBA_ClientNodeID = 23;
    public const ushort DBA_ClientPlayerData = 24;
    public const ushort DBA_ClientDelPlayerOK = 25;
    public const ushort DBA_ClientAllFamily = 26;
    public const ushort DBA_ClientNewFamily = 27;
    public const ushort DBA_ClientChangeFamily = 28;
    public const ushort DBA_ClientRemoveFamily = 29;
    public const ushort DBA_ClientFamilyAllMember = 30;
    public const ushort DBA_ClientAddFamilyMember = 31;
    public const ushort DBA_ClientMigrationCharacter = 32;
    public const ushort DBA_ClientChannelMsg = 33;
    public const ushort DBA_ClientElfData = 34;
    public const ushort DBA_ClientShortcut = 35;
    public const ushort DBA_ClientFinishPlayerData = 36;
    public const ushort DBA_ClientCollection = 37;
    public const ushort DBA_ClientFamilyAllMessage = 38;
    public const ushort DBA_ClientAllLover = 39;
    public const ushort DBA_ClientAllTerritory = 40;
    public const ushort DBA_ClientFamilyStorage = 41;
    public const ushort DBA_ClientSpellMaster = 42;
    public const ushort DBA_ClientTransportData = 43;
    public const ushort DBA_ClientRecommendedEvents = 44;
    public const ushort DBA_ReloadTranslate = 45;
    public const ushort DBA_ClientFamilyCropInfo = 46;
    public const ushort DBA_ClientRaceTeamInfo = 47;
    public const ushort DBA_ClientMentorship = 48;
    public const ushort ZMis_MissionServerRefreshRecommendedEvents = 49;
    public const ushort ZMis_MissionServerUpdateRecommendedEvents = 50;
    public const ushort ZMis_ZoneServerUpdateRecommendedEvents = 51;
    public const ushort ZMis_ZoneServerReportID = 55;
    public const ushort ZMis_MissionServerIDReport = 56;
}
