namespace GFTools.Common.Protocol.CommandIDs;

public static class ZoneServerCommands {
    public enum CZ_Commands : ushort {
        NC_CZ_ClientAchievementUpdate = 478,
        NC_CZ_ClientAddAppellation = 407,
        NC_CZ_ClientAltarState = 472,
        NC_CZ_ClientAskIdentifyGold = 374,
        NC_CZ_ClientAskRepairEquipGold = 284,
        NC_CZ_ClientAskRepairOneItemGold = 353,
        NC_CZ_ClientAttrRefresh = 309,
        NC_CZ_ClientAuctionBuyList = 436,
        NC_CZ_ClientAuctionBuyOK = 437,
        NC_CZ_ClientAuctionCancelOK = 438,
        NC_CZ_ClientAuctionHouse = 441,
        NC_CZ_ClientAuctionSellList = 439,
        NC_CZ_ClientAuctionSellResult = 440,
        NC_CZ_ClientBagDueDate = 399,
        NC_CZ_ClientBattleMemberPosition = 473,
        NC_CZ_ClientBattlefieldJoinResult = 469,
        NC_CZ_ClientBattlefieldList = 467,
        NC_CZ_ClientBattlefieldMemberInfo = 474,
        NC_CZ_ClientBattlefieldResult = 470,
        NC_CZ_ClientBattlefieldTeamJoin = 367,
        NC_CZ_ClientBattlefieldUpdateScore = 471,
        NC_CZ_ClientBeastsTowerUpdate = 600,
        NC_CZ_ClientBlockMailGMOP = 628,
        NC_CZ_ClientBuyBackList = 512,
        NC_CZ_ClientBuyUp = 320,
        NC_CZ_ClientCanCloseConnection = 326,
        NC_CZ_ClientCanJoinTeam = 520,
        NC_CZ_ClientCanLogout = 368,
        NC_CZ_ClientChairCombineCheckOK = 606,
        NC_CZ_ClientChairCombineOpenUI = 605,
        NC_CZ_ClientChangeAppellation = 405,
        NC_CZ_ClientChangeElf = 442,
        NC_CZ_ClientChangeEquip = 288,
        NC_CZ_ClientChangeFamily = 357,
        NC_CZ_ClientChangeSpecificSpell = 581,
        NC_CZ_ClientChannelMsg = 339,
        NC_CZ_ClientChannelMsgTell = 504,
        NC_CZ_ClientCheckEnterLimitNode = 625,
        NC_CZ_ClientCoRideInvite = 525,
        NC_CZ_ClientCoSitChairInvite = 604,
        NC_CZ_ClientCommandFailReturn = 420,
        NC_CZ_ClientContinuedSpellEnd = 632,
        NC_CZ_ClientCreatePKPalaceUI = 549,
        NC_CZ_ClientCreateProgressUI = 553,
        NC_CZ_ClientDestShutdown = 308,
        NC_CZ_ClientDetailAttrRefresh = 623,
        NC_CZ_ClientDie = 317,
        NC_CZ_ClientDisplayChar = 419,
        NC_CZ_ClientDisplayCharSimple = 335,
        NC_CZ_ClientDisplayDialogView = 297,
        NC_CZ_ClientDisplayMonster = 282,
        NC_CZ_ClientDropItem = 287,
        NC_CZ_ClientDuelBegin = 458,
        NC_CZ_ClientDuelRequest = 456,
        NC_CZ_ClientDuelRequestResult = 457,
        NC_CZ_ClientDuelResult = 459,
        NC_CZ_ClientDynamicEventData = 567,
        NC_CZ_ClientEffectReport = 305,
        NC_CZ_ClientElfAction = 453,
        NC_CZ_ClientElfAdd = 424,
        NC_CZ_ClientElfAttrRefresh = 535,
        NC_CZ_ClientElfBattleMode = 536,
        NC_CZ_ClientElfBoxingOpen = 513,
        NC_CZ_ClientElfBoxingUpdateBet = 516,
        NC_CZ_ClientElfBoxingUpdateSchedule = 514,
        NC_CZ_ClientElfBoxingUpdateState = 515,
        NC_CZ_ClientElfCastEnchant = 275,
        NC_CZ_ClientElfCoolDowns = 575,
        NC_CZ_ClientElfDecompose = 432,
        NC_CZ_ClientElfEvent = 428,
        NC_CZ_ClientElfGames = 487,
        NC_CZ_ClientElfGoToWork = 431,
        NC_CZ_ClientElfLotteryWeek = 505,
        NC_CZ_ClientElfRacingUpdate = 596,
        NC_CZ_ClientElfReturnEffect = 454,
        NC_CZ_ClientElfReturnOK = 425,
        NC_CZ_ClientElfSchoolResult = 566,
        NC_CZ_ClientElfSpell = 572,
        NC_CZ_ClientElfSpellCoolDown = 574,
        NC_CZ_ClientElfSpellPoint = 571,
        NC_CZ_ClientElfSpellShortcuts = 573,
        NC_CZ_ClientElfStoneUse = 433,
        NC_CZ_ClientElfTempleChallengeNotify = 630,
        NC_CZ_ClientElfUpdateAttr = 429,
        NC_CZ_ClientElfUpdateSkill = 430,
        NC_CZ_ClientElfWorkResult = 426,
        NC_CZ_ClientElfWorkResultEnd = 427,
        NC_CZ_ClientElftabletAttrRefresh = 621,
        NC_CZ_ClientElftabletComboUpdate = 622,
        NC_CZ_ClientEnchantAdd = 312,
        NC_CZ_ClientEnchantRemove = 313,
        NC_CZ_ClientEnchantReset = 327,
        NC_CZ_ClientEnchantUpdate = 314,
        NC_CZ_ClientEnterBattlefield = 468,
        NC_CZ_ClientEnterElfReturn = 450,
        NC_CZ_ClientEnterExchageItemService = 377,
        NC_CZ_ClientEnterFamilyBattleSchedule = 495,
        NC_CZ_ClientEnterFamilyCreation = 358,
        NC_CZ_ClientEnterFamilyRecruit = 507,
        NC_CZ_ClientEnterFamilyStorage = 489,
        NC_CZ_ClientEnterIdentifyShop = 376,
        NC_CZ_ClientEnterInlayShop = 381,
        NC_CZ_ClientEnterIsleCreation = 539,
        NC_CZ_ClientEnterIsleStorage = 562,
        NC_CZ_ClientEnterLimitNodeTimesNextRestoreTime = 626,
        NC_CZ_ClientEnterMessageBoard = 460,
        NC_CZ_ClientEnterMissionList = 398,
        NC_CZ_ClientEnterNodeElfContainer = 435,
        NC_CZ_ClientEnterNodeElfInfo = 423,
        NC_CZ_ClientEnterNodeElfInventory = 559,
        NC_CZ_ClientEnterNodeElftablet = 620,
        NC_CZ_ClientEnterNodeEquipAndSpell = 323,
        NC_CZ_ClientEnterNodeInventory = 324,
        NC_CZ_ClientEnterNodeMiniGameData = 510,
        NC_CZ_ClientEnterNodeNodeData = 325,
        NC_CZ_ClientEnterNodePlayerData = 322,
        NC_CZ_ClientEnterNodeShortcut = 362,
        NC_CZ_ClientEnterRepairShop = 361,
        NC_CZ_ClientEnterShop = 271,
        NC_CZ_ClientEnterSpellShop = 360,
        NC_CZ_ClientEnterStorage = 369,
        NC_CZ_ClientEnterStrengthen = 443,
        NC_CZ_ClientEnterTransport = 402,
        NC_CZ_ClientEquipTrainItemChanged = 555,
        NC_CZ_ClientFamilyBattleInfo = 494,
        NC_CZ_ClientFamilyBattleMemberPos = 500,
        NC_CZ_ClientFamilyBattleResult = 499,
        NC_CZ_ClientFamilyBattleSchedule = 496,
        NC_CZ_ClientFamilyFarmHireds = 544,
        NC_CZ_ClientFamilyFarmInfo = 537,
        NC_CZ_ClientFamilyFlag = 488,
        NC_CZ_ClientFamilyStorageData = 490,
        NC_CZ_ClientFamilyStorageDeleteItem = 492,
        NC_CZ_ClientFamilyStorageLog = 493,
        NC_CZ_ClientFamilyStoragePutItem = 491,
        NC_CZ_ClientFamilyTransformCloseUI = 589,
        NC_CZ_ClientFamilyTransformOpenUI = 588,
        NC_CZ_ClientFamilyUnionInvite = 497,
        NC_CZ_ClientFamilyWishingResult = 618,
        NC_CZ_ClientFamilyWishingWellOpenUI = 617,
        NC_CZ_ClientFightKingCommand = 576,
        NC_CZ_ClientFishOP = 547,
        NC_CZ_ClientFlagModify = 315,
        NC_CZ_ClientGameTimer = 554,
        NC_CZ_ClientGetSelectLifeTarget = 455,
        NC_CZ_ClientGetSpell = 298,
        NC_CZ_ClientGetStorageData = 370,
        NC_CZ_ClientGladiatorCount = 570,
        NC_CZ_ClientGoto = 278,
        NC_CZ_ClientHello = 477,
        NC_CZ_ClientIdentifyItem = 375,
        NC_CZ_ClientInlayItemResult = 382,
        NC_CZ_ClientIsleFarm = 545,
        NC_CZ_ClientItemExchangeOP = 601,
        NC_CZ_ClientItemRent = 466,
        NC_CZ_ClientItemUnLock = 421,
        NC_CZ_ClientItemUse = 316,
        NC_CZ_ClientLeaveNode = 307,
        NC_CZ_ClientLevelUp = 296,
        NC_CZ_ClientLifeEradicate = 280,
        NC_CZ_ClientLogoutResp = 366,
        NC_CZ_ClientLookDetailAttr = 624,
        NC_CZ_ClientLookEquip = 465,
        NC_CZ_ClientLotteryGoOpen = 557,
        NC_CZ_ClientLotteryGoUpdateReward = 556,
        NC_CZ_ClientLoveChallengeEnrollRequest = 610,
        NC_CZ_ClientLoverBreak = 485,
        NC_CZ_ClientLoverInfo = 484,
        NC_CZ_ClientLoverInvite = 482,
        NC_CZ_ClientLoverPosition = 486,
        NC_CZ_ClientLoverUpdate = 483,
        NC_CZ_ClientLuckyBarChoseElf = 354,
        NC_CZ_ClientLuckyBarPlayResult = 266,
        NC_CZ_ClientLuckyBarPlayRunEnd = 267,
        NC_CZ_ClientLuckyBarUpdateStatus = 268,
        NC_CZ_ClientLuckyBarUpdateUI = 550,
        NC_CZ_ClientLuckyStarBet = 264,
        NC_CZ_ClientLuckyStarInfo = 265,
        NC_CZ_ClientMailDeleteResult = 411,
        NC_CZ_ClientMailGetGoldOK = 415,
        NC_CZ_ClientMailGetItemOK = 414,
        NC_CZ_ClientMailList = 409,
        NC_CZ_ClientMailOpenBox = 408,
        NC_CZ_ClientMailRead = 410,
        NC_CZ_ClientMailReceive = 413,
        NC_CZ_ClientMailReturnResult = 418,
        NC_CZ_ClientMailSendResult = 412,
        NC_CZ_ClientMeleeAttack = 283,
        NC_CZ_ClientMentorshipUpdateMentor = 593,
        NC_CZ_ClientMentorshipUpdateSelf = 592,
        NC_CZ_ClientMentorshipUpdateStudent = 594,
        NC_CZ_ClientMessageDeleteResult = 464,
        NC_CZ_ClientMessageList = 461,
        NC_CZ_ClientMessageRead = 463,
        NC_CZ_ClientMessageWriteResult = 462,
        NC_CZ_ClientMigrationDone = 393,
        NC_CZ_ClientMiniGameStart = 269,
        NC_CZ_ClientMiniGameStopPlay = 270,
        NC_CZ_ClientMissionStates = 359,
        NC_CZ_ClientMobChangeAI = 451,
        NC_CZ_ClientMobTransform = 391,
        NC_CZ_ClientModelModify = 295,
        NC_CZ_ClientModifyAttr = 340,
        NC_CZ_ClientModifyItemDurability = 304,
        NC_CZ_ClientModifyItemInfo = 380,
        NC_CZ_ClientModifyItemStrengthen = 447,
        NC_CZ_ClientMoveChar = 502,
        NC_CZ_ClientMovePrediction = 338,
        NC_CZ_ClientNodeExit = 306,
        NC_CZ_ClientNonSafeQuit = 334,
        NC_CZ_ClientOpenFamilyFarmInterface = 538,
        NC_CZ_ClientOpenIsleAltarUI = 542,
        NC_CZ_ClientOpenIsleFarmUI = 551,
        NC_CZ_ClientOpenIsleStatueUI = 543,
        NC_CZ_ClientOpenIsleUI = 540,
        NC_CZ_ClientOpenIsleWorkElfUI = 586,
        NC_CZ_ClientOpenMarryDlg = 560,
        NC_CZ_ClientOpenWriteMessage = 509,
        NC_CZ_ClientPKPalaceRankInfo = 634,
        NC_CZ_ClientPing = 273,
        NC_CZ_ClientPlayEffect = 394,
        NC_CZ_ClientPlayElfPetAction = 475,
        NC_CZ_ClientPlayMonsterAction = 272,
        NC_CZ_ClientPlaySound = 511,
        NC_CZ_ClientPlayerAction = 303,
        NC_CZ_ClientPlayerEmotion = 319,
        NC_CZ_ClientPutItemIntoElfInventory = 558,
        NC_CZ_ClientPutItemIntoInventory = 286,
        NC_CZ_ClientPutItemIntoIsleStorage = 561,
        NC_CZ_ClientPutItemIntoStorage = 371,
        NC_CZ_ClientPutItemIntoWnd = 608,
        NC_CZ_ClientQueryNpc = 373,
        NC_CZ_ClientRERandInfo = 568,
        NC_CZ_ClientRaceRankInfo = 579,
        NC_CZ_ClientRaceTeamInfo = 577,
        NC_CZ_ClientRainbowRoadGameEvents = 614,
        NC_CZ_ClientRainbowRoadGameNotify = 613,
        NC_CZ_ClientRainbowRoadTeamAllMembersInfo = 612,
        NC_CZ_ClientRainbowRoadTeamInviteResult = 615,
        NC_CZ_ClientRainbowRoadTeamNotify = 611,
        NC_CZ_ClientRankInfo = 506,
        NC_CZ_ClientRebirthCheck = 598,
        NC_CZ_ClientReceiveShortcutOfPage = 363,
        NC_CZ_ClientRecommendedEvents = 522,
        NC_CZ_ClientRemoveRollIndex = 564,
        NC_CZ_ClientReplaceShortcutPage = 629,
        NC_CZ_ClientResetCoord = 281,
        NC_CZ_ClientResetSpell = 378,
        NC_CZ_ClientRespondPlayerPrestigeExchange = 627,
        NC_CZ_ClientRestore = 285,
        NC_CZ_ClientResurrect = 352,
        NC_CZ_ClientRevive = 318,
        NC_CZ_ClientRideCombineCheckOK = 585,
        NC_CZ_ClientRideCombineOpenUI = 584,
        NC_CZ_ClientRideTrainInfo = 569,
        NC_CZ_ClientRollTreasure = 526,
        NC_CZ_ClientSBFInfo = 534,
        NC_CZ_ClientSBFInvite = 533,
        NC_CZ_ClientSBFPlayerQuery = 532,
        NC_CZ_ClientSBFWndOpen = 531,
        NC_CZ_ClientSafeQuitCancel = 332,
        NC_CZ_ClientSafeQuitResp = 333,
        NC_CZ_ClientSay = 279,
        NC_CZ_ClientScreenMessage = 481,
        NC_CZ_ClientSearchInfo = 422,
        NC_CZ_ClientSearchTeamInfo = 519,
        NC_CZ_ClientSeeChar = 503,
        NC_CZ_ClientSeeContinuedSpell = 631,
        NC_CZ_ClientSeeMob = 311,
        NC_CZ_ClientSeeTreasure = 498,
        NC_CZ_ClientSelectFamilyEmblem = 395,
        NC_CZ_ClientSellOut = 321,
        NC_CZ_ClientSetChairCombineEquip = 607,
        NC_CZ_ClientSetCollectionPointAbility = 563,
        NC_CZ_ClientSetCrystalComboEquip = 616,
        NC_CZ_ClientSetMissionBookOpen = 521,
        NC_CZ_ClientSetRideCombineEquip = 583,
        NC_CZ_ClientSetSpellStone = 448,
        NC_CZ_ClientShowSceneEventState = 599,
        NC_CZ_ClientSloganUpdate = 385,
        NC_CZ_ClientSpecialSpell = 524,
        NC_CZ_ClientSpellBlastOK = 300,
        NC_CZ_ClientSpellBlastToLife = 301,
        NC_CZ_ClientSpellBlastToLocation = 310,
        NC_CZ_ClientSpellBreak = 299,
        NC_CZ_ClientSpellCast = 434,
        NC_CZ_ClientSpellCastOK = 290,
        NC_CZ_ClientSpellFlyToLife = 633,
        NC_CZ_ClientSpellHitToLife = 293,
        NC_CZ_ClientSpellLoopCastStop = 372,
        NC_CZ_ClientSpellStorageUI = 597,
        NC_CZ_ClientStopEffect = 609,
        NC_CZ_ClientStopKeepingSpell = 602,
        NC_CZ_ClientStorageExpandResult = 384,
        NC_CZ_ClientStrengthenCasting = 444,
        NC_CZ_ClientStrengthenItemCancel = 445,
        NC_CZ_ClientStrengthenItemResult = 446,
        NC_CZ_ClientStudentEnrollRequest = 595,
        NC_CZ_ClientSummonPet = 449,
        NC_CZ_ClientSwitchItemLocationOK = 289,
        NC_CZ_ClientTeamAllMembersInfo = 336,
        NC_CZ_ClientTeamInfo = 392,
        NC_CZ_ClientTeamInviteNotice = 330,
        NC_CZ_ClientTeamInviteResult = 331,
        NC_CZ_ClientTeamLeaved = 329,
        NC_CZ_ClientTeamMemberEnchant = 383,
        NC_CZ_ClientTeamMemberPosition = 401,
        NC_CZ_ClientTeamNewMemberInfo = 337,
        NC_CZ_ClientTeamRadarAttention = 397,
        NC_CZ_ClientTeamRecruitMsg = 518,
        NC_CZ_ClientTerritoryInfo = 528,
        NC_CZ_ClientTerritoryKilledInfo = 530,
        NC_CZ_ClientTerritoryQuery = 529,
        NC_CZ_ClientTextOutput = 277,
        NC_CZ_ClientTextOutputIndex = 328,
        NC_CZ_ClientTextOutputItem = 508,
        NC_CZ_ClientTicketInvalid = 276,
        NC_CZ_ClientTradeAddItem = 344,
        NC_CZ_ClientTradeAddItemFail = 346,
        NC_CZ_ClientTradeCancel = 350,
        NC_CZ_ClientTradeComplete = 351,
        NC_CZ_ClientTradeConfirm = 349,
        NC_CZ_ClientTradeModifyGold = 347,
        NC_CZ_ClientTradeModifyGoldFail = 348,
        NC_CZ_ClientTradeReady = 403,
        NC_CZ_ClientTradeRemoveItem = 345,
        NC_CZ_ClientTradeRequest = 342,
        NC_CZ_ClientTradeReset = 364,
        NC_CZ_ClientTradeStart = 343,
        NC_CZ_ClientTradeUnConfirm = 404,
        NC_CZ_ClientTreasureDisappear = 341,
        NC_CZ_ClientTreasurePickupOK = 396,
        NC_CZ_ClientTurnChar = 452,
        NC_CZ_ClientUpdateAdvancedAbility = 476,
        NC_CZ_ClientUpdateAppellation = 406,
        NC_CZ_ClientUpdateAttr = 291,
        NC_CZ_ClientUpdateBFData = 479,
        NC_CZ_ClientUpdateCharacterSetting = 619,
        NC_CZ_ClientUpdateCollection = 274,
        NC_CZ_ClientUpdateCoolDown = 379,
        NC_CZ_ClientUpdateDailyAwards = 582,
        NC_CZ_ClientUpdateDetailAttrGroup = 292,
        NC_CZ_ClientUpdateElfBotOpen = 501,
        NC_CZ_ClientUpdateElfSchoolScore = 565,
        NC_CZ_ClientUpdateEquipment = 294,
        NC_CZ_ClientUpdateFreeTicket = 590,
        NC_CZ_ClientUpdateHealthOnlineTime = 480,
        NC_CZ_ClientUpdateHelloInfo = 591,
        NC_CZ_ClientUpdateIsle = 541,
        NC_CZ_ClientUpdateIsleCrop = 552,
        NC_CZ_ClientUpdateIsleFarm = 546,
        NC_CZ_ClientUpdateLottery = 387,
        NC_CZ_ClientUpdateMissionState = 400,
        NC_CZ_ClientUpdateNPCSymbols = 356,
        NC_CZ_ClientUpdatePKPalace = 548,
        NC_CZ_ClientUpdatePrestigeData = 517,
        NC_CZ_ClientUpdateRaceTeam = 578,
        NC_CZ_ClientUpdateRecommendedEvents = 523,
        NC_CZ_ClientUpdateSpellGroupData = 603,
        NC_CZ_ClientUpdateStarAvenue = 587,
        NC_CZ_ClientUpdateSystemVar = 355,
        NC_CZ_ClientUpdateUpanishads = 580,
        NC_CZ_ClientUpdateZoneMonster = 527,
        NC_CZ_ClientUseItemTime = 416,
        NC_CZ_ClientUseItemTimeBreak = 417,
        NC_CZ_ClientUseSkillPointOK = 365,
        NC_CZ_ClientVendorClose = 302,
        NC_CZ_ClientVendorCloseView = 386,
        NC_CZ_ClientVendorContainer = 390,
        NC_CZ_ClientVendorStatus = 388,
        NC_CZ_ClientVendorUpdateView = 389,
        NC_CZ_ZoneServerAddEnterTimes = 255,
        NC_CZ_ZoneServerAskIdentifyGold = 89,
        NC_CZ_ZoneServerAskRepairEquipGold = 72,
        NC_CZ_ZoneServerAskRepairOneItemGold = 74,
        NC_CZ_ZoneServerAskVendor = 96,
        NC_CZ_ZoneServerAskVendorContainer = 97,
        NC_CZ_ZoneServerAuctionBuy = 137,
        NC_CZ_ZoneServerAuctionBuyQuery = 136,
        NC_CZ_ZoneServerAuctionCancel = 140,
        NC_CZ_ZoneServerAuctionSell = 139,
        NC_CZ_ZoneServerAuctionSellQuery = 138,
        NC_CZ_ZoneServerAutoSortItem = 219,
        NC_CZ_ZoneServerBFListQuery = 162,
        NC_CZ_ZoneServerBFTeamJoinAnswer = 163,
        NC_CZ_ZoneServerBagDueDate = 115,
        NC_CZ_ZoneServerBattleStatusLog = 258,
        NC_CZ_ZoneServerBattlefieldJoin = 159,
        NC_CZ_ZoneServerBattlefieldLeave = 161,
        NC_CZ_ZoneServerBeastsTowerOP = 234,
        NC_CZ_ZoneServerBlockMailOP = 261,
        NC_CZ_ZoneServerBuyBackOpen = 180,
        NC_CZ_ZoneServerBuyItems = 50,
        NC_CZ_ZoneServerBuySpell = 79,
        NC_CZ_ZoneServerChairCombineCheck = 237,
        NC_CZ_ZoneServerChairCombineCloseUI = 239,
        NC_CZ_ZoneServerChairCombineData = 238,
        NC_CZ_ZoneServerChangeUpanishads = 220,
        NC_CZ_ZoneServerChannelMsg = 58,
        NC_CZ_ZoneServerCheckNodeExit = 43,
        NC_CZ_ZoneServerCheckUpdateLottery = 169,
        NC_CZ_ZoneServerClientCrash = 210,
        NC_CZ_ZoneServerCloseMissionBrief = 70,
        NC_CZ_ZoneServerCoRideInvite = 188,
        NC_CZ_ZoneServerCoSitChairInvite = 236,
        NC_CZ_ZoneServerDailyAwardOP = 221,
        NC_CZ_ZoneServerDivideItem = 110,
        NC_CZ_ZoneServerDropItem = 34,
        NC_CZ_ZoneServerDuelRequest = 149,
        NC_CZ_ZoneServerDuelRequestAnswer = 150,
        NC_CZ_ZoneServerEcho = 83,
        NC_CZ_ZoneServerElfBattleOperate = 194,
        NC_CZ_ZoneServerElfBoxingPlay = 184,
        NC_CZ_ZoneServerElfBoxingUpdateSchedule = 182,
        NC_CZ_ZoneServerElfBoxingUpdateState = 183,
        NC_CZ_ZoneServerElfCheckData = 134,
        NC_CZ_ZoneServerElfGames = 14,
        NC_CZ_ZoneServerElfRacingOP = 230,
        NC_CZ_ZoneServerElfReturn = 131,
        NC_CZ_ZoneServerElfSceneFurnitureUpdate = 259,
        NC_CZ_ZoneServerElfSpellOP = 214,
        NC_CZ_ZoneServerElfStoneUpdate = 128,
        NC_CZ_ZoneServerElfStoneUse = 129,
        NC_CZ_ZoneServerElfTalk = 151,
        NC_CZ_ZoneServerElfTempleChallengeNotify = 262,
        NC_CZ_ZoneServerElfWork = 130,
        NC_CZ_ZoneServerElfWorkResultOK = 133,
        NC_CZ_ZoneServerElftabletComboActive = 250,
        NC_CZ_ZoneServerElftabletSacrifice = 249,
        NC_CZ_ZoneServerEnchantCancel = 111,
        NC_CZ_ZoneServerEnchantUpdate = 46,
        NC_CZ_ZoneServerEnterBattlefieldAnswer = 160,
        NC_CZ_ZoneServerEnterLimitNode = 253,
        NC_CZ_ZoneServerEnterNodeElfContainer = 135,
        NC_CZ_ZoneServerEnterNodeElfInfo = 132,
        NC_CZ_ZoneServerEnterNodeElfInventory = 206,
        NC_CZ_ZoneServerEnterNodeElftablet = 248,
        NC_CZ_ZoneServerEnterNodeEquipAndSpell = 52,
        NC_CZ_ZoneServerEnterNodeInventory = 53,
        NC_CZ_ZoneServerEnterNodeMiniGameData = 105,
        NC_CZ_ZoneServerEnterNodePlayerData = 54,
        NC_CZ_ZoneServerEnterNodeShortcut = 80,
        NC_CZ_ZoneServerEquipTrainSetItem = 203,
        NC_CZ_ZoneServerExchangeItemPin = 91,
        NC_CZ_ZoneServerFamilyBattleQuit = 28,
        NC_CZ_ZoneServerFamilyBattleSchedule = 24,
        NC_CZ_ZoneServerFamilyBattleScheduleExit = 25,
        NC_CZ_ZoneServerFamilyCreate = 76,
        NC_CZ_ZoneServerFamilyDonateMoney = 64,
        NC_CZ_ZoneServerFamilyFarmOp = 196,
        NC_CZ_ZoneServerFamilyFlag = 15,
        NC_CZ_ZoneServerFamilyStatue = 9,
        NC_CZ_ZoneServerFamilyStorageGetItem = 21,
        NC_CZ_ZoneServerFamilyStoragePutItem = 22,
        NC_CZ_ZoneServerFamilyUnionInvite = 26,
        NC_CZ_ZoneServerFamilyUnionInviteResult = 27,
        NC_CZ_ZoneServerFamilyUseSpell = 2,
        NC_CZ_ZoneServerFamilyWishing = 245,
        NC_CZ_ZoneServerFightKingCommand = 215,
        NC_CZ_ZoneServerFishOP = 198,
        NC_CZ_ZoneServerGetCharacterSetting = 247,
        NC_CZ_ZoneServerGetCollection = 4,
        NC_CZ_ZoneServerGetSelectLifeTarget = 148,
        NC_CZ_ZoneServerGetShortcutOfPage = 82,
        NC_CZ_ZoneServerGetStorageData = 87,
        NC_CZ_ZoneServerGiveUpMission = 78,
        NC_CZ_ZoneServerGotoFamilyTreeInstance = 227,
        NC_CZ_ZoneServerHello = 178,
        NC_CZ_ZoneServerHelloOP = 228,
        NC_CZ_ZoneServerIdentifyItem = 90,
        NC_CZ_ZoneServerInlayItem = 92,
        NC_CZ_ZoneServerIsleOP = 197,
        NC_CZ_ZoneServerItemExchangeOP = 235,
        NC_CZ_ZoneServerItemLockCheck = 8,
        NC_CZ_ZoneServerItemMallReceivableEnter = 95,
        NC_CZ_ZoneServerItemMallUseItem = 109,
        NC_CZ_ZoneServerItemUse = 47,
        NC_CZ_ZoneServerJoinGladiator = 212,
        NC_CZ_ZoneServerKusoCombine = 202,
        NC_CZ_ZoneServerLeaveFamilyStorage = 23,
        NC_CZ_ZoneServerLeaveShop = 88,
        NC_CZ_ZoneServerLogoutReq = 84,
        NC_CZ_ZoneServerLookDetailAttr = 158,
        NC_CZ_ZoneServerLookEquip = 157,
        NC_CZ_ZoneServerLotteryGoGetItem = 205,
        NC_CZ_ZoneServerLotteryGoPlay = 204,
        NC_CZ_ZoneServerLoveChallengeOP = 241,
        NC_CZ_ZoneServerLoverBreak = 13,
        NC_CZ_ZoneServerLoverInvite = 10,
        NC_CZ_ZoneServerLoverMarryAnswer = 207,
        NC_CZ_ZoneServerLoverMessage = 11,
        NC_CZ_ZoneServerLuckyBarChoseElf = 172,
        NC_CZ_ZoneServerLuckyBarPlay = 173,
        NC_CZ_ZoneServerLuckyBarPlayRunEnd = 175,
        NC_CZ_ZoneServerLuckyBarPlayerGetMoney = 201,
        NC_CZ_ZoneServerLuckyBarUpdateStatus = 176,
        NC_CZ_ZoneServerLuckyStarChose = 170,
        NC_CZ_ZoneServerLuckyStarQuery = 171,
        NC_CZ_ZoneServerMailDelete = 124,
        NC_CZ_ZoneServerMailGetGold = 126,
        NC_CZ_ZoneServerMailGetItem = 125,
        NC_CZ_ZoneServerMailQuery = 122,
        NC_CZ_ZoneServerMailRead = 123,
        NC_CZ_ZoneServerMailReturn = 127,
        NC_CZ_ZoneServerMailSend = 7,
        NC_CZ_ZoneServerMeleeAttack = 33,
        NC_CZ_ZoneServerMentorshipOP = 229,
        NC_CZ_ZoneServerMessageDelete = 155,
        NC_CZ_ZoneServerMessageExit = 156,
        NC_CZ_ZoneServerMessageListQuery = 152,
        NC_CZ_ZoneServerMessageRead = 154,
        NC_CZ_ZoneServerMessageWrite = 153,
        NC_CZ_ZoneServerMigrationDone = 32,
        NC_CZ_ZoneServerMiniGameStartPlay = 200,
        NC_CZ_ZoneServerMiniGameStopPlay = 174,
        NC_CZ_ZoneServerMissionGoto = 166,
        NC_CZ_ZoneServerMissionListOp = 113,
        NC_CZ_ZoneServerMoveSelf = 30,
        NC_CZ_ZoneServerNodeGroupReset = 181,
        NC_CZ_ZoneServerOpenStarAvenueUI = 226,
        NC_CZ_ZoneServerOpenUIModifyOP = 143,
        NC_CZ_ZoneServerPKPalaceOP = 199,
        NC_CZ_ZoneServerPing = 177,
        NC_CZ_ZoneServerPlayerAction = 42,
        NC_CZ_ZoneServerPlayerEmotion = 49,
        NC_CZ_ZoneServerPlayerPrestigeExchange = 260,
        NC_CZ_ZoneServerQueryAppellation = 121,
        NC_CZ_ZoneServerQueryBattlefieldData = 65,
        NC_CZ_ZoneServerQueryCollection = 5,
        NC_CZ_ZoneServerQueryEnterTimesUpdate = 254,
        NC_CZ_ZoneServerQueryGladiatorCount = 213,
        NC_CZ_ZoneServerQueryLoverInfo = 12,
        NC_CZ_ZoneServerQueryMissionStates = 77,
        NC_CZ_ZoneServerQueryPKPalaceRankInfo = 263,
        NC_CZ_ZoneServerQueryRecommendedEvents = 187,
        NC_CZ_ZoneServerRaceOP = 216,
        NC_CZ_ZoneServerRaceRankInfoQuery = 217,
        NC_CZ_ZoneServerRainbowRoadGameNotify = 243,
        NC_CZ_ZoneServerRainbowRoadTeamNotify = 242,
        NC_CZ_ZoneServerRankInfoQuery = 168,
        NC_CZ_ZoneServerRebirth = 232,
        NC_CZ_ZoneServerReceiveTicket = 29,
        NC_CZ_ZoneServerRepairEquipment = 73,
        NC_CZ_ZoneServerRepairOneItem = 75,
        NC_CZ_ZoneServerReplyDialog = 39,
        NC_CZ_ZoneServerReportProcessInfos = 93,
        NC_CZ_ZoneServerResurrect = 71,
        NC_CZ_ZoneServerRevive = 48,
        NC_CZ_ZoneServerRideCombineCheck = 225,
        NC_CZ_ZoneServerRideCombineCloseUI = 224,
        NC_CZ_ZoneServerRideCombineData = 222,
        NC_CZ_ZoneServerRideTrainInfo = 211,
        NC_CZ_ZoneServerRollTreasureReturn = 189,
        NC_CZ_ZoneServerSBFInviteInfo = 192,
        NC_CZ_ZoneServerSBFOp = 193,
        NC_CZ_ZoneServerSafeQuitCancel = 56,
        NC_CZ_ZoneServerSafeQuitCountDownOver = 57,
        NC_CZ_ZoneServerSafeQuitReq = 55,
        NC_CZ_ZoneServerSaveCollection = 3,
        NC_CZ_ZoneServerSceneEventStateOP = 233,
        NC_CZ_ZoneServerSearchCondition = 0,
        NC_CZ_ZoneServerSearchOpt = 1,
        NC_CZ_ZoneServerSearchTeam = 186,
        NC_CZ_ZoneServerSellItems = 51,
        NC_CZ_ZoneServerSendMotionDataErrorLog = 256,
        NC_CZ_ZoneServerSetAAPoint = 164,
        NC_CZ_ZoneServerSetAARate = 165,
        NC_CZ_ZoneServerSetCarvingStyle = 252,
        NC_CZ_ZoneServerSetChairCombineEquip = 240,
        NC_CZ_ZoneServerSetCollectionPointAbility = 209,
        NC_CZ_ZoneServerSetCrystalComboEquip = 244,
        NC_CZ_ZoneServerSetFamilyEmblem = 108,
        NC_CZ_ZoneServerSetPVP = 16,
        NC_CZ_ZoneServerSetRideCombineEquip = 223,
        NC_CZ_ZoneServerSetSpellStone = 144,
        NC_CZ_ZoneServerSloganUpdate = 98,
        NC_CZ_ZoneServerSpellBreak = 41,
        NC_CZ_ZoneServerSpellCastToLife = 37,
        NC_CZ_ZoneServerSpellCastToLocation = 44,
        NC_CZ_ZoneServerSpellCastToNearby = 85,
        NC_CZ_ZoneServerSpellCastToNowhere = 45,
        NC_CZ_ZoneServerSpellStorageOP = 231,
        NC_CZ_ZoneServerStateCancel = 145,
        NC_CZ_ZoneServerStorageDeposit = 86,
        NC_CZ_ZoneServerStorageExpand = 94,
        NC_CZ_ZoneServerStrengthenClose = 142,
        NC_CZ_ZoneServerStrengthenItem = 141,
        NC_CZ_ZoneServerSwitchItemLocation = 35,
        NC_CZ_ZoneServerTalkToNPC = 38,
        NC_CZ_ZoneServerTargetUpdate = 146,
        NC_CZ_ZoneServerTeamChangeLeader = 116,
        NC_CZ_ZoneServerTeamInvite = 18,
        NC_CZ_ZoneServerTeamInviteAnswer = 19,
        NC_CZ_ZoneServerTeamInviteCancel = 20,
        NC_CZ_ZoneServerTeamLeave = 17,
        NC_CZ_ZoneServerTeamOperation = 104,
        NC_CZ_ZoneServerTeamRadarAttention = 112,
        NC_CZ_ZoneServerTeamRecruitMsg = 185,
        NC_CZ_ZoneServerTerritoryJoin = 190,
        NC_CZ_ZoneServerTerritoryQuery = 191,
        NC_CZ_ZoneServerTextCommand = 31,
        NC_CZ_ZoneServerTradeAddItem = 62,
        NC_CZ_ZoneServerTradeCancel = 69,
        NC_CZ_ZoneServerTradeConfirm = 68,
        NC_CZ_ZoneServerTradeModifyGold = 67,
        NC_CZ_ZoneServerTradeReady = 117,
        NC_CZ_ZoneServerTradeRemoveItem = 66,
        NC_CZ_ZoneServerTradeRequest = 60,
        NC_CZ_ZoneServerTradeRequestAccept = 61,
        NC_CZ_ZoneServerTradeReset = 179,
        NC_CZ_ZoneServerTradeUnConfirm = 118,
        NC_CZ_ZoneServerTransport = 114,
        NC_CZ_ZoneServerTransportToPoint = 208,
        NC_CZ_ZoneServerTreasurePickup = 59,
        NC_CZ_ZoneServerTurnSelf = 147,
        NC_CZ_ZoneServerUpdateAppellation = 119,
        NC_CZ_ZoneServerUpdateAppellationTop = 120,
        NC_CZ_ZoneServerUpdateArenaScore = 195,
        NC_CZ_ZoneServerUpdateBotData = 167,
        NC_CZ_ZoneServerUpdateElfPickSetting = 246,
        NC_CZ_ZoneServerUpdateEquipment = 36,
        NC_CZ_ZoneServerUpdateFamily = 107,
        NC_CZ_ZoneServerUpdateOptionSettings = 251,
        NC_CZ_ZoneServerUpdateShortcut = 81,
        NC_CZ_ZoneServerUseArenaPoint = 218,
        NC_CZ_ZoneServerUseMoneyResetSpellAA = 257,
        NC_CZ_ZoneServerUseSkillPoint = 40,
        NC_CZ_ZoneServerVendorBuy = 101,
        NC_CZ_ZoneServerVendorClose = 99,
        NC_CZ_ZoneServerVendorCloseVending = 103,
        NC_CZ_ZoneServerVendorCloseView = 100,
        NC_CZ_ZoneServerVendorSellItem = 102,
        NC_CZ_ZoneServerVendorUseItem = 106,
        NC_CZ_ZoneServerVictoryDeclaration = 6,
        NC_CZ_ZoneServerWhoIs = 63
    }

    public const ushort NC_CG_ClientChannel = 5;
    public const ushort NC_CG_ClientCharLocate = 6;
    public const ushort NC_CG_ClientCharacter = 3;
    public const ushort NC_CG_ClientCharacterList = 2;
    public const ushort NC_CG_ClientDataTest = 0;
    public const ushort NC_CG_ClientGetContainerItem = 0;
    public const ushort NC_CG_ClientGetMail = 0;
    public const ushort NC_CG_ClientGetMissionState = 0;
    public const ushort NC_CG_ClientGetMoney = 0;
    public const ushort NC_CG_ClientTextOutput = 4;
    public const ushort NC_CG_ServerLogin = 1;
    public const ushort NC_CG_ServerTextCommand = 0;
    public const ushort NC_DBA_AgentDBACommand = 20;
    public const ushort NC_DBA_ClientAddFamilyMember = 31;
    public const ushort NC_DBA_ClientAllFamily = 26;
    public const ushort NC_DBA_ClientAllLover = 39;
    public const ushort NC_DBA_ClientAllTerritory = 40;
    public const ushort NC_DBA_ClientChangeFamily = 28;
    public const ushort NC_DBA_ClientChannelMsg = 33;
    public const ushort NC_DBA_ClientCollection = 37;
    public const ushort NC_DBA_ClientContainer = 21;
    public const ushort NC_DBA_ClientDelPlayerOK = 25;
    public const ushort NC_DBA_ClientElfData = 34;
    public const ushort NC_DBA_ClientEnchant = 22;
    public const ushort NC_DBA_ClientFamilyAllMember = 30;
    public const ushort NC_DBA_ClientFamilyAllMessage = 38;
    public const ushort NC_DBA_ClientFamilyCropInfo = 46;
    public const ushort NC_DBA_ClientFamilyStorage = 41;
    public const ushort NC_DBA_ClientFinishPlayerData = 36;
    public const ushort NC_DBA_ClientMentorship = 48;
    public const ushort NC_DBA_ClientMigrationCharacter = 32;
    public const ushort NC_DBA_ClientNewFamily = 27;
    public const ushort NC_DBA_ClientNodeID = 23;
    public const ushort NC_DBA_ClientPlayerData = 24;
    public const ushort NC_DBA_ClientRaceTeamInfo = 47;
    public const ushort NC_DBA_ClientRecommendedEvents = 44;
    public const ushort NC_DBA_ClientRemoveFamily = 29;
    public const ushort NC_DBA_ClientShortcut = 35;
    public const ushort NC_DBA_ClientSpellMaster = 42;
    public const ushort NC_DBA_ClientTransportData = 43;
    public const ushort NC_DBA_ReloadTranslate = 45;
    public const ushort NC_MW_MissionServerTextExCmd = 14;
    public const ushort NC_MW_MissionServerTextExCmdRemoteWorld = 15;
    public const ushort NC_MW_MissionServerTextExCmdRemoteZone = 16;
    public const ushort NC_MW_WorldServerCheckFamilyInvite = 7;
    public const ushort NC_MW_WorldServerCrossZone = 3;
    public const ushort NC_MW_WorldServerFBMsgUpdate = 9;
    public const ushort NC_MW_WorldServerFunctionSwitchUpdate = 13;
    public const ushort NC_MW_WorldServerItemMallMailCheckOK = 2;
    public const ushort NC_MW_WorldServerItemMallMailSendResult = 1;
    public const ushort NC_MW_WorldServerTell = 0;
    public const ushort NC_MW_WorldServerTextExCmd = 10;
    public const ushort NC_MW_WorldServerTextExCmdRemoteWorld = 11;
    public const ushort NC_MW_WorldServerTextExCmdRemoteZone = 12;
    public const ushort NC_MW_WorldServerUpdateBlackList = 4;
    public const ushort NC_MW_WorldServerUpdateFriendMember = 6;
    public const ushort NC_MW_WorldServerUpdatePrestigeData = 5;
    public const ushort NC_MW_WorldTextCommand = 19;
    public const ushort NC_T_ClientGetTicket = 2;
    public const ushort NC_T_ClientUseTicket = 3;
    public const ushort NC_T_ServerGetTicket = 0;
    public const ushort NC_T_ServerUseTicket = 1;
    public const ushort NC_ZM_MonsterServerListRebornMonster = 148;
    public const ushort NC_ZM_MonsterServerModifyRebornMonster = 150;
    public const ushort NC_ZM_MonsterServerMonsterDieReport = 147;
    public const ushort NC_ZM_MonsterServerMonsterReport = 146;
    public const ushort NC_ZM_MonsterServerRegenerationReport = 156;
    public const ushort NC_ZM_MonsterServerRemoveNode = 153;
    public const ushort NC_ZM_MonsterServerRemoveRebornMonster = 151;
    public const ushort NC_ZM_MonsterServerSetRebornMonster = 149;
    public const ushort NC_ZM_MonsterServerStartCharRegenerate = 154;
    public const ushort NC_ZM_MonsterServerStopCharRegenerate = 155;
    public const ushort NC_ZM_MonsterServerUnRegRebornMonster = 152;
    public const ushort NC_ZM_ZoneServerAddIsleRecord = 127;
    public const ushort NC_ZM_ZoneServerCharRegenerate = 67;
    public const ushort NC_ZM_ZoneServerCropInfos = 130;
    public const ushort NC_ZM_ZoneServerFamilyFarmHireds = 126;
    public const ushort NC_ZM_ZoneServerIsleDBA = 124;
    public const ushort NC_ZM_ZoneServerIsleFishGrounds = 128;
    public const ushort NC_ZM_ZoneServerMessageToCharacter = 66;
    public const ushort NC_ZM_ZoneServerRebornMonster = 64;
    public const ushort NC_ZM_ZoneServerReportMonster = 63;
    public const ushort NC_ZM_ZoneServerSetRebornMonsterResult = 65;
    public const ushort NC_ZM_ZoneServerUpdateIsle = 125;
    public const ushort NC_ZM_ZoneServerUpdateIsleFishGround = 129;
    public const ushort NC_ZM_ZoneServerUpdatePKList = 17;
    public const ushort NC_ZMis_MissionServerAccountSharedOP = 189;
    public const ushort NC_ZMis_MissionServerAddFamilyMessage = 54;
    public const ushort NC_ZMis_MissionServerAddIsleRecord = 182;
    public const ushort NC_ZMis_MissionServerAuctionBuyQuery = 191;
    public const ushort NC_ZMis_MissionServerBattlefieldClose = 171;
    public const ushort NC_ZMis_MissionServerBattlefieldEraseMember = 170;
    public const ushort NC_ZMis_MissionServerBattlefieldJoin = 169;
    public const ushort NC_ZMis_MissionServerBattlefieldList = 172;
    public const ushort NC_ZMis_MissionServerBattlefieldTeamJoinAnswer = 175;
    public const ushort NC_ZMis_MissionServerBattlefieldUpdateStatus = 174;
    public const ushort NC_ZMis_MissionServerBeastsTowerOP = 187;
    public const ushort NC_ZMis_MissionServerBlockMailOP = 190;
    public const ushort NC_ZMis_MissionServerChannelMsg = 176;
    public const ushort NC_ZMis_MissionServerCheckFamilyInvite = 8;
    public const ushort NC_ZMis_MissionServerCloseMissionBrief = 158;
    public const ushort NC_ZMis_MissionServerCrossZone = 166;
    public const ushort NC_ZMis_MissionServerCrossZoneRequest = 165;
    public const ushort NC_ZMis_MissionServerDelayMessage = 186;
    public const ushort NC_ZMis_MissionServerEnterBattlefieldAnswer = 173;
    public const ushort NC_ZMis_MissionServerFamilyBattleDataUpdate = 168;
    public const ushort NC_ZMis_MissionServerFamilyBattleResult = 167;
    public const ushort NC_ZMis_MissionServerFightKingCommand = 184;
    public const ushort NC_ZMis_MissionServerGiveUpMission = 160;
    public const ushort NC_ZMis_MissionServerIDReport = 56;
    public const ushort NC_ZMis_MissionServerIsleOP = 181;
    public const ushort NC_ZMis_MissionServerItemExchange = 188;
    public const ushort NC_ZMis_MissionServerItemMallMailCheck = 53;
    public const ushort NC_ZMis_MissionServerItemMallMailSend = 52;
    public const ushort NC_ZMis_MissionServerListDialogue = 142;
    public const ushort NC_ZMis_MissionServerLuckyStarBet = 145;
    public const ushort NC_ZMis_MissionServerMailSend = 162;
    public const ushort NC_ZMis_MissionServerMessageWrite = 164;
    public const ushort NC_ZMis_MissionServerMigrationDone = 159;
    public const ushort NC_ZMis_MissionServerMobDieReport = 161;
    public const ushort NC_ZMis_MissionServerNodeCreate = 57;
    public const ushort NC_ZMis_MissionServerOnDialogueSelected = 143;
    public const ushort NC_ZMis_MissionServerQueryLuckyStar = 144;
    public const ushort NC_ZMis_MissionServerRaceResult = 185;
    public const ushort NC_ZMis_MissionServerRefreshRecommendedEvents = 49;
    public const ushort NC_ZMis_MissionServerRemoteClient = 177;
    public const ushort NC_ZMis_MissionServerRemovePMS = 157;
    public const ushort NC_ZMis_MissionServerSendSystemMail = 163;
    public const ushort NC_ZMis_MissionServerTextExCmd = 178;
    public const ushort NC_ZMis_MissionServerTextExCmdRemoteWorld = 179;
    public const ushort NC_ZMis_MissionServerTextExCmdRemoteZone = 180;
    public const ushort NC_ZMis_MissionServerUpdateElfSchoolScore = 183;
    public const ushort NC_ZMis_MissionServerUpdatePKList = 18;
    public const ushort NC_ZMis_MissionServerUpdateRecommendedEvents = 50;
    public const ushort NC_ZMis_ZoneServerAccountSharedUpdate = 139;
    public const ushort NC_ZMis_ZoneServerAchievementUpdate = 92;
    public const ushort NC_ZMis_ZoneServerAuctionBuyList = 81;
    public const ushort NC_ZMis_ZoneServerAuctionBuyOK = 82;
    public const ushort NC_ZMis_ZoneServerAuctionCancelOK = 83;
    public const ushort NC_ZMis_ZoneServerAuctionSellList = 84;
    public const ushort NC_ZMis_ZoneServerAuctionSellResult = 85;
    public const ushort NC_ZMis_ZoneServerBattlefieldChangeCharNum = 108;
    public const ushort NC_ZMis_ZoneServerBattlefieldEraseMember = 104;
    public const ushort NC_ZMis_ZoneServerBattlefieldJoinResult = 100;
    public const ushort NC_ZMis_ZoneServerBattlefieldList = 103;
    public const ushort NC_ZMis_ZoneServerBattlefieldSetup = 107;
    public const ushort NC_ZMis_ZoneServerBattlefieldTeamJoin = 105;
    public const ushort NC_ZMis_ZoneServerBeastsTowerUpdate = 137;
    public const ushort NC_ZMis_ZoneServerBroadCastElfSchoolFinalResult = 134;
    public const ushort NC_ZMis_ZoneServerBuyBackGetItem = 112;
    public const ushort NC_ZMis_ZoneServerBuyBackList = 111;
    public const ushort NC_ZMis_ZoneServerBuybackInitAllocate = 120;
    public const ushort NC_ZMis_ZoneServerCharNotQuit = 91;
    public const ushort NC_ZMis_ZoneServerCrossZoneResult = 93;
    public const ushort NC_ZMis_ZoneServerDeallocateItemID = 113;
    public const ushort NC_ZMis_ZoneServerDropItem = 77;
    public const ushort NC_ZMis_ZoneServerEnterBattlefield = 101;
    public const ushort NC_ZMis_ZoneServerEnterBattlefieldAnswer = 106;
    public const ushort NC_ZMis_ZoneServerFamilyBattleInfo = 97;
    public const ushort NC_ZMis_ZoneServerFamilyBattleSchedule = 98;
    public const ushort NC_ZMis_ZoneServerFamilyStorageLog = 96;
    public const ushort NC_ZMis_ZoneServerFamilyStorageUpdate = 95;
    public const ushort NC_ZMis_ZoneServerFamilyUnionInvite = 99;
    public const ushort NC_ZMis_ZoneServerFightKingCommand = 131;
    public const ushort NC_ZMis_ZoneServerFunctionSwitchUpdate = 140;
    public const ushort NC_ZMis_ZoneServerGMToolGetInfo = 192;
    public const ushort NC_ZMis_ZoneServerGMToolGetMail = 194;
    public const ushort NC_ZMis_ZoneServerGMToolGetMission = 193;
    public const ushort NC_ZMis_ZoneServerItemExchangeUpdate = 138;
    public const ushort NC_ZMis_ZoneServerListDialogue = 58;
    public const ushort NC_ZMis_ZoneServerLoverUpdate = 94;
    public const ushort NC_ZMis_ZoneServerLuckyStarBet = 110;
    public const ushort NC_ZMis_ZoneServerMailDeleteResult = 73;
    public const ushort NC_ZMis_ZoneServerMailGetGoldOK = 79;
    public const ushort NC_ZMis_ZoneServerMailGetItemOK = 78;
    public const ushort NC_ZMis_ZoneServerMailList = 71;
    public const ushort NC_ZMis_ZoneServerMailRead = 72;
    public const ushort NC_ZMis_ZoneServerMailReceive = 75;
    public const ushort NC_ZMis_ZoneServerMailReturnResult = 80;
    public const ushort NC_ZMis_ZoneServerMailSendResult = 74;
    public const ushort NC_ZMis_ZoneServerMessageDeleteResult = 90;
    public const ushort NC_ZMis_ZoneServerMessageList = 87;
    public const ushort NC_ZMis_ZoneServerMessageRead = 89;
    public const ushort NC_ZMis_ZoneServerMessageWriteResult = 88;
    public const ushort NC_ZMis_ZoneServerNPCTalkCheck = 118;
    public const ushort NC_ZMis_ZoneServerPutItem = 76;
    public const ushort NC_ZMis_ZoneServerQueryLuckyStar = 62;
    public const ushort NC_ZMis_ZoneServerRaceRankInfo = 133;
    public const ushort NC_ZMis_ZoneServerRankAwardTestResult = 195;
    public const ushort NC_ZMis_ZoneServerRankInfo = 109;
    public const ushort NC_ZMis_ZoneServerRefreshTerritoryNodeEnchant = 141;
    public const ushort NC_ZMis_ZoneServerRefreshTreeEnchant = 135;
    public const ushort NC_ZMis_ZoneServerRemoteClient = 114;
    public const ushort NC_ZMis_ZoneServerReplyDialogue = 59;
    public const ushort NC_ZMis_ZoneServerReportID = 55;
    public const ushort NC_ZMis_ZoneServerSearchInfo = 86;
    public const ushort NC_ZMis_ZoneServerShowSceneEventState = 136;
    public const ushort NC_ZMis_ZoneServerStartBattlefield = 102;
    public const ushort NC_ZMis_ZoneServerTerritoryInfo = 121;
    public const ushort NC_ZMis_ZoneServerTerritoryJoin = 123;
    public const ushort NC_ZMis_ZoneServerTerritoryQuery = 122;
    public const ushort NC_ZMis_ZoneServerTextExCmd = 115;
    public const ushort NC_ZMis_ZoneServerTextExCmdRemoteWorld = 117;
    public const ushort NC_ZMis_ZoneServerTextExCmdRemoteZone = 116;
    public const ushort NC_ZMis_ZoneServerTextOutput = 61;
    public const ushort NC_ZMis_ZoneServerTextOutputIndex = 69;
    public const ushort NC_ZMis_ZoneServerTransitionCommands = 60;
    public const ushort NC_ZMis_ZoneServerUpdateMissionState = 70;
    public const ushort NC_ZMis_ZoneServerUpdateNPCSymbols = 68;
    public const ushort NC_ZMis_ZoneServerUpdatePrestigeData = 119;
    public const ushort NC_ZMis_ZoneServerUpdateRaceTeam = 132;
    public const ushort NC_ZMis_ZoneServerUpdateRecommendedEvents = 51;
    public const ushort NC_ZW_WorldServerAllUsers = 2;
    public const ushort NC_ZW_WorldServerChannelMsg = 8;
    public const ushort NC_ZW_WorldServerCharacterArrived = 4;
    public const ushort NC_ZW_WorldServerFBMsgUpdate = 14;
    public const ushort NC_ZW_WorldServerFamilyCreation = 9;
    public const ushort NC_ZW_WorldServerGetCloneItemID = 13;
    public const ushort NC_ZW_WorldServerIDReport = 0;
    public const ushort NC_ZW_WorldServerItemMallReceieveAttempt = 12;
    public const ushort NC_ZW_WorldServerLogout = 10;
    public const ushort NC_ZW_WorldServerNotifyEntry = 3;
    public const ushort NC_ZW_WorldServerResetTime = 5;
    public const ushort NC_ZW_WorldServerReturnToCharacterList = 6;
    public const ushort NC_ZW_WorldServerTeamLeavedNotify = 7;
    public const ushort NC_ZW_WorldServerTell = 1;
    public const ushort NC_ZW_WorldServerTextCommand = 11;
    public const ushort NC_ZW_WorldServerTextExCmd = 15;
    public const ushort NC_ZW_ZoneServerChangeFamily = 21;
    public const ushort NC_ZW_ZoneServerChannelMsg = 20;
    public const ushort NC_ZW_ZoneServerCharacterArrive = 18;
    public const ushort NC_ZW_ZoneServerCharacterArrivedDest = 19;
    public const ushort NC_ZW_ZoneServerDestShutdown = 17;
    public const ushort NC_ZW_ZoneServerFamilyUseSpell = 28;
    public const ushort NC_ZW_ZoneServerGMToolGetInfo = 31;
    public const ushort NC_ZW_ZoneServerGetCloneItemID = 26;
    public const ushort NC_ZW_ZoneServerItemMallReceieveAttempt = 25;
    public const ushort NC_ZW_ZoneServerNewFamily = 22;
    public const ushort NC_ZW_ZoneServerRemoveFamily = 23;
    public const ushort NC_ZW_ZoneServerReportID = 16;
    public const ushort NC_ZW_ZoneServerTextCommand = 24;
    public const ushort NC_ZW_ZoneServerTextExCmd = 30;
    public const ushort NC_ZW_ZoneServerUpdateFortuneBag = 27;
    public const ushort NC_ZW_ZoneServerUpdateLottery = 29;
}
