namespace GFTools.Common.Protocol.CommandIDs;

public static class ZoneServerCommands {
    // Client <-> ZoneServer
    public enum CZ_Commands : ushort {
        CZ_ClientAchievementUpdate = 478,
        CZ_ClientAddAppellation = 407,
        CZ_ClientAltarState = 472,
        CZ_ClientAskIdentifyGold = 374,
        CZ_ClientAskRepairEquipGold = 284,
        CZ_ClientAskRepairOneItemGold = 353,
        CZ_ClientAttrRefresh = 309,
        CZ_ClientAuctionBuyList = 436,
        CZ_ClientAuctionBuyOK = 437,
        CZ_ClientAuctionCancelOK = 438,
        CZ_ClientAuctionHouse = 441,
        CZ_ClientAuctionSellList = 439,
        CZ_ClientAuctionSellResult = 440,
        CZ_ClientBagDueDate = 399,
        CZ_ClientBattleMemberPosition = 473,
        CZ_ClientBattlefieldJoinResult = 469,
        CZ_ClientBattlefieldList = 467,
        CZ_ClientBattlefieldMemberInfo = 474,
        CZ_ClientBattlefieldResult = 470,
        CZ_ClientBattlefieldTeamJoin = 367,
        CZ_ClientBattlefieldUpdateScore = 471,
        CZ_ClientBeastsTowerUpdate = 600,
        CZ_ClientBlockMailGMOP = 628,
        CZ_ClientBuyBackList = 512,
        CZ_ClientBuyUp = 320,
        CZ_ClientCanCloseConnection = 326,
        CZ_ClientCanJoinTeam = 520,
        CZ_ClientCanLogout = 368,
        CZ_ClientChairCombineCheckOK = 606,
        CZ_ClientChairCombineOpenUI = 605,
        CZ_ClientChangeAppellation = 405,
        CZ_ClientChangeElf = 442,
        CZ_ClientChangeEquip = 288,
        CZ_ClientChangeFamily = 357,
        CZ_ClientChangeSpecificSpell = 581,
        CZ_ClientChannelMsg = 339,
        CZ_ClientChannelMsgTell = 504,
        CZ_ClientCheckEnterLimitNode = 625,
        CZ_ClientCoRideInvite = 525,
        CZ_ClientCoSitChairInvite = 604,
        CZ_ClientCommandFailReturn = 420,
        CZ_ClientContinuedSpellEnd = 632,
        CZ_ClientCreatePKPalaceUI = 549,
        CZ_ClientCreateProgressUI = 553,
        CZ_ClientDestShutdown = 308,
        CZ_ClientDetailAttrRefresh = 623,
        CZ_ClientDie = 317,
        CZ_ClientDisplayChar = 419,
        CZ_ClientDisplayCharSimple = 335,
        CZ_ClientDisplayDialogView = 297,
        CZ_ClientDisplayMonster = 282,
        CZ_ClientDropItem = 287,
        CZ_ClientDuelBegin = 458,
        CZ_ClientDuelRequest = 456,
        CZ_ClientDuelRequestResult = 457,
        CZ_ClientDuelResult = 459,
        CZ_ClientDynamicEventData = 567,
        CZ_ClientEffectReport = 305,
        CZ_ClientElfAction = 453,
        CZ_ClientElfAdd = 424,
        CZ_ClientElfAttrRefresh = 535,
        CZ_ClientElfBattleMode = 536,
        CZ_ClientElfBoxingOpen = 513,
        CZ_ClientElfBoxingUpdateBet = 516,
        CZ_ClientElfBoxingUpdateSchedule = 514,
        CZ_ClientElfBoxingUpdateState = 515,
        CZ_ClientElfCastEnchant = 275,
        CZ_ClientElfCoolDowns = 575,
        CZ_ClientElfDecompose = 432,
        CZ_ClientElfEvent = 428,
        CZ_ClientElfGames = 487,
        CZ_ClientElfGoToWork = 431,
        CZ_ClientElfLotteryWeek = 505,
        CZ_ClientElfRacingUpdate = 596,
        CZ_ClientElfReturnEffect = 454,
        CZ_ClientElfReturnOK = 425,
        CZ_ClientElfSchoolResult = 566,
        CZ_ClientElfSpell = 572,
        CZ_ClientElfSpellCoolDown = 574,
        CZ_ClientElfSpellPoint = 571,
        CZ_ClientElfSpellShortcuts = 573,
        CZ_ClientElfStoneUse = 433,
        CZ_ClientElfTempleChallengeNotify = 630,
        CZ_ClientElfUpdateAttr = 429,
        CZ_ClientElfUpdateSkill = 430,
        CZ_ClientElfWorkResult = 426,
        CZ_ClientElfWorkResultEnd = 427,
        CZ_ClientElftabletAttrRefresh = 621,
        CZ_ClientElftabletComboUpdate = 622,
        CZ_ClientEnchantAdd = 312,
        CZ_ClientEnchantRemove = 313,
        CZ_ClientEnchantReset = 327,
        CZ_ClientEnchantUpdate = 314,
        CZ_ClientEnterBattlefield = 468,
        CZ_ClientEnterElfReturn = 450,
        CZ_ClientEnterExchageItemService = 377,
        CZ_ClientEnterFamilyBattleSchedule = 495,
        CZ_ClientEnterFamilyCreation = 358,
        CZ_ClientEnterFamilyRecruit = 507,
        CZ_ClientEnterFamilyStorage = 489,
        CZ_ClientEnterIdentifyShop = 376,
        CZ_ClientEnterInlayShop = 381,
        CZ_ClientEnterIsleCreation = 539,
        CZ_ClientEnterIsleStorage = 562,
        CZ_ClientEnterLimitNodeTimesNextRestoreTime = 626,
        CZ_ClientEnterMessageBoard = 460,
        CZ_ClientEnterMissionList = 398,
        CZ_ClientEnterNodeElfContainer = 435,
        CZ_ClientEnterNodeElfInfo = 423,
        CZ_ClientEnterNodeElfInventory = 559,
        CZ_ClientEnterNodeElftablet = 620,
        CZ_ClientEnterNodeEquipAndSpell = 323,
        CZ_ClientEnterNodeInventory = 324,
        CZ_ClientEnterNodeMiniGameData = 510,
        CZ_ClientEnterNodeNodeData = 325,
        CZ_ClientEnterNodePlayerData = 322,
        CZ_ClientEnterNodeShortcut = 362,
        CZ_ClientEnterRepairShop = 361,
        CZ_ClientEnterShop = 271,
        CZ_ClientEnterSpellShop = 360,
        CZ_ClientEnterStorage = 369,
        CZ_ClientEnterStrengthen = 443,
        CZ_ClientEnterTransport = 402,
        CZ_ClientEquipTrainItemChanged = 555,
        CZ_ClientFamilyBattleInfo = 494,
        CZ_ClientFamilyBattleMemberPos = 500,
        CZ_ClientFamilyBattleResult = 499,
        CZ_ClientFamilyBattleSchedule = 496,
        CZ_ClientFamilyFarmHireds = 544,
        CZ_ClientFamilyFarmInfo = 537,
        CZ_ClientFamilyFlag = 488,
        CZ_ClientFamilyStorageData = 490,
        CZ_ClientFamilyStorageDeleteItem = 492,
        CZ_ClientFamilyStorageLog = 493,
        CZ_ClientFamilyStoragePutItem = 491,
        CZ_ClientFamilyTransformCloseUI = 589,
        CZ_ClientFamilyTransformOpenUI = 588,
        CZ_ClientFamilyUnionInvite = 497,
        CZ_ClientFamilyWishingResult = 618,
        CZ_ClientFamilyWishingWellOpenUI = 617,
        CZ_ClientFightKingCommand = 576,
        CZ_ClientFishOP = 547,
        CZ_ClientFlagModify = 315,
        CZ_ClientGameTimer = 554,
        CZ_ClientGetSelectLifeTarget = 455,
        CZ_ClientGetSpell = 298,
        CZ_ClientGetStorageData = 370,
        CZ_ClientGladiatorCount = 570,
        CZ_ClientGoto = 278,
        CZ_ClientHello = 477,
        CZ_ClientIdentifyItem = 375,
        CZ_ClientInlayItemResult = 382,
        CZ_ClientIsleFarm = 545,
        CZ_ClientItemExchangeOP = 601,
        CZ_ClientItemRent = 466,
        CZ_ClientItemUnLock = 421,
        CZ_ClientItemUse = 316,
        CZ_ClientLeaveNode = 307,
        CZ_ClientLevelUp = 296,
        CZ_ClientLifeEradicate = 280,
        CZ_ClientLogoutResp = 366,
        CZ_ClientLookDetailAttr = 624,
        CZ_ClientLookEquip = 465,
        CZ_ClientLotteryGoOpen = 557,
        CZ_ClientLotteryGoUpdateReward = 556,
        CZ_ClientLoveChallengeEnrollRequest = 610,
        CZ_ClientLoverBreak = 485,
        CZ_ClientLoverInfo = 484,
        CZ_ClientLoverInvite = 482,
        CZ_ClientLoverPosition = 486,
        CZ_ClientLoverUpdate = 483,
        CZ_ClientLuckyBarChoseElf = 354,
        CZ_ClientLuckyBarPlayResult = 266,
        CZ_ClientLuckyBarPlayRunEnd = 267,
        CZ_ClientLuckyBarUpdateStatus = 268,
        CZ_ClientLuckyBarUpdateUI = 550,
        CZ_ClientLuckyStarBet = 264,
        CZ_ClientLuckyStarInfo = 265,
        CZ_ClientMailDeleteResult = 411,
        CZ_ClientMailGetGoldOK = 415,
        CZ_ClientMailGetItemOK = 414,
        CZ_ClientMailList = 409,
        CZ_ClientMailOpenBox = 408,
        CZ_ClientMailRead = 410,
        CZ_ClientMailReceive = 413,
        CZ_ClientMailReturnResult = 418,
        CZ_ClientMailSendResult = 412,
        CZ_ClientMeleeAttack = 283,
        CZ_ClientMentorshipUpdateMentor = 593,
        CZ_ClientMentorshipUpdateSelf = 592,
        CZ_ClientMentorshipUpdateStudent = 594,
        CZ_ClientMessageDeleteResult = 464,
        CZ_ClientMessageList = 461,
        CZ_ClientMessageRead = 463,
        CZ_ClientMessageWriteResult = 462,
        CZ_ClientMigrationDone = 393,
        CZ_ClientMiniGameStart = 269,
        CZ_ClientMiniGameStopPlay = 270,
        CZ_ClientMissionStates = 359,
        CZ_ClientMobChangeAI = 451,
        CZ_ClientMobTransform = 391,
        CZ_ClientModelModify = 295,
        CZ_ClientModifyAttr = 340,
        CZ_ClientModifyItemDurability = 304,
        CZ_ClientModifyItemInfo = 380,
        CZ_ClientModifyItemStrengthen = 447,
        CZ_ClientMoveChar = 502,
        CZ_ClientMovePrediction = 338,
        CZ_ClientNodeExit = 306,
        CZ_ClientNonSafeQuit = 334,
        CZ_ClientOpenFamilyFarmInterface = 538,
        CZ_ClientOpenIsleAltarUI = 542,
        CZ_ClientOpenIsleFarmUI = 551,
        CZ_ClientOpenIsleStatueUI = 543,
        CZ_ClientOpenIsleUI = 540,
        CZ_ClientOpenIsleWorkElfUI = 586,
        CZ_ClientOpenMarryDlg = 560,
        CZ_ClientOpenWriteMessage = 509,
        CZ_ClientPKPalaceRankInfo = 634,
        CZ_ClientPing = 273,
        CZ_ClientPlayEffect = 394,
        CZ_ClientPlayElfPetAction = 475,
        CZ_ClientPlayMonsterAction = 272,
        CZ_ClientPlaySound = 511,
        CZ_ClientPlayerAction = 303,
        CZ_ClientPlayerEmotion = 319,
        CZ_ClientPutItemIntoElfInventory = 558,
        CZ_ClientPutItemIntoInventory = 286,
        CZ_ClientPutItemIntoIsleStorage = 561,
        CZ_ClientPutItemIntoStorage = 371,
        CZ_ClientPutItemIntoWnd = 608,
        CZ_ClientQueryNpc = 373,
        CZ_ClientRERandInfo = 568,
        CZ_ClientRaceRankInfo = 579,
        CZ_ClientRaceTeamInfo = 577,
        CZ_ClientRainbowRoadGameEvents = 614,
        CZ_ClientRainbowRoadGameNotify = 613,
        CZ_ClientRainbowRoadTeamAllMembersInfo = 612,
        CZ_ClientRainbowRoadTeamInviteResult = 615,
        CZ_ClientRainbowRoadTeamNotify = 611,
        CZ_ClientRankInfo = 506,
        CZ_ClientRebirthCheck = 598,
        CZ_ClientReceiveShortcutOfPage = 363,
        CZ_ClientRecommendedEvents = 522,
        CZ_ClientRemoveRollIndex = 564,
        CZ_ClientReplaceShortcutPage = 629,
        CZ_ClientResetCoord = 281,
        CZ_ClientResetSpell = 378,
        CZ_ClientRespondPlayerPrestigeExchange = 627,
        CZ_ClientRestore = 285,
        CZ_ClientResurrect = 352,
        CZ_ClientRevive = 318,
        CZ_ClientRideCombineCheckOK = 585,
        CZ_ClientRideCombineOpenUI = 584,
        CZ_ClientRideTrainInfo = 569,
        CZ_ClientRollTreasure = 526,
        CZ_ClientSBFInfo = 534,
        CZ_ClientSBFInvite = 533,
        CZ_ClientSBFPlayerQuery = 532,
        CZ_ClientSBFWndOpen = 531,
        CZ_ClientSafeQuitCancel = 332,
        CZ_ClientSafeQuitResp = 333,
        CZ_ClientSay = 279,
        CZ_ClientScreenMessage = 481,
        CZ_ClientSearchInfo = 422,
        CZ_ClientSearchTeamInfo = 519,
        CZ_ClientSeeChar = 503,
        CZ_ClientSeeContinuedSpell = 631,
        CZ_ClientSeeMob = 311,
        CZ_ClientSeeTreasure = 498,
        CZ_ClientSelectFamilyEmblem = 395,
        CZ_ClientSellOut = 321,
        CZ_ClientSetChairCombineEquip = 607,
        CZ_ClientSetCollectionPointAbility = 563,
        CZ_ClientSetCrystalComboEquip = 616,
        CZ_ClientSetMissionBookOpen = 521,
        CZ_ClientSetRideCombineEquip = 583,
        CZ_ClientSetSpellStone = 448,
        CZ_ClientShowSceneEventState = 599,
        CZ_ClientSloganUpdate = 385,
        CZ_ClientSpecialSpell = 524,
        CZ_ClientSpellBlastOK = 300,
        CZ_ClientSpellBlastToLife = 301,
        CZ_ClientSpellBlastToLocation = 310,
        CZ_ClientSpellBreak = 299,
        CZ_ClientSpellCast = 434,
        CZ_ClientSpellCastOK = 290,
        CZ_ClientSpellFlyToLife = 633,
        CZ_ClientSpellHitToLife = 293,
        CZ_ClientSpellLoopCastStop = 372,
        CZ_ClientSpellStorageUI = 597,
        CZ_ClientStopEffect = 609,
        CZ_ClientStopKeepingSpell = 602,
        CZ_ClientStorageExpandResult = 384,
        CZ_ClientStrengthenCasting = 444,
        CZ_ClientStrengthenItemCancel = 445,
        CZ_ClientStrengthenItemResult = 446,
        CZ_ClientStudentEnrollRequest = 595,
        CZ_ClientSummonPet = 449,
        CZ_ClientSwitchItemLocationOK = 289,
        CZ_ClientTeamAllMembersInfo = 336,
        CZ_ClientTeamInfo = 392,
        CZ_ClientTeamInviteNotice = 330,
        CZ_ClientTeamInviteResult = 331,
        CZ_ClientTeamLeaved = 329,
        CZ_ClientTeamMemberEnchant = 383,
        CZ_ClientTeamMemberPosition = 401,
        CZ_ClientTeamNewMemberInfo = 337,
        CZ_ClientTeamRadarAttention = 397,
        CZ_ClientTeamRecruitMsg = 518,
        CZ_ClientTerritoryInfo = 528,
        CZ_ClientTerritoryKilledInfo = 530,
        CZ_ClientTerritoryQuery = 529,
        CZ_ClientTextOutput = 277,
        CZ_ClientTextOutputIndex = 328,
        CZ_ClientTextOutputItem = 508,
        CZ_ClientTicketInvalid = 276,
        CZ_ClientTradeAddItem = 344,
        CZ_ClientTradeAddItemFail = 346,
        CZ_ClientTradeCancel = 350,
        CZ_ClientTradeComplete = 351,
        CZ_ClientTradeConfirm = 349,
        CZ_ClientTradeModifyGold = 347,
        CZ_ClientTradeModifyGoldFail = 348,
        CZ_ClientTradeReady = 403,
        CZ_ClientTradeRemoveItem = 345,
        CZ_ClientTradeRequest = 342,
        CZ_ClientTradeReset = 364,
        CZ_ClientTradeStart = 343,
        CZ_ClientTradeUnConfirm = 404,
        CZ_ClientTreasureDisappear = 341,
        CZ_ClientTreasurePickupOK = 396,
        CZ_ClientTurnChar = 452,
        CZ_ClientUpdateAdvancedAbility = 476,
        CZ_ClientUpdateAppellation = 406,
        CZ_ClientUpdateAttr = 291,
        CZ_ClientUpdateBFData = 479,
        CZ_ClientUpdateCharacterSetting = 619,
        CZ_ClientUpdateCollection = 274,
        CZ_ClientUpdateCoolDown = 379,
        CZ_ClientUpdateDailyAwards = 582,
        CZ_ClientUpdateDetailAttrGroup = 292,
        CZ_ClientUpdateElfBotOpen = 501,
        CZ_ClientUpdateElfSchoolScore = 565,
        CZ_ClientUpdateEquipment = 294,
        CZ_ClientUpdateFreeTicket = 590,
        CZ_ClientUpdateHealthOnlineTime = 480,
        CZ_ClientUpdateHelloInfo = 591,
        CZ_ClientUpdateIsle = 541,
        CZ_ClientUpdateIsleCrop = 552,
        CZ_ClientUpdateIsleFarm = 546,
        CZ_ClientUpdateLottery = 387,
        CZ_ClientUpdateMissionState = 400,
        CZ_ClientUpdateNPCSymbols = 356,
        CZ_ClientUpdatePKPalace = 548,
        CZ_ClientUpdatePrestigeData = 517,
        CZ_ClientUpdateRaceTeam = 578,
        CZ_ClientUpdateRecommendedEvents = 523,
        CZ_ClientUpdateSpellGroupData = 603,
        CZ_ClientUpdateStarAvenue = 587,
        CZ_ClientUpdateSystemVar = 355,
        CZ_ClientUpdateUpanishads = 580,
        CZ_ClientUpdateZoneMonster = 527,
        CZ_ClientUseItemTime = 416,
        CZ_ClientUseItemTimeBreak = 417,
        CZ_ClientUseSkillPointOK = 365,
        CZ_ClientVendorClose = 302,
        CZ_ClientVendorCloseView = 386,
        CZ_ClientVendorContainer = 390,
        CZ_ClientVendorStatus = 388,
        CZ_ClientVendorUpdateView = 389,
        CZ_ZoneServerAddEnterTimes = 255,
        CZ_ZoneServerAskIdentifyGold = 89,
        CZ_ZoneServerAskRepairEquipGold = 72,
        CZ_ZoneServerAskRepairOneItemGold = 74,
        CZ_ZoneServerAskVendor = 96,
        CZ_ZoneServerAskVendorContainer = 97,
        CZ_ZoneServerAuctionBuy = 137,
        CZ_ZoneServerAuctionBuyQuery = 136,
        CZ_ZoneServerAuctionCancel = 140,
        CZ_ZoneServerAuctionSell = 139,
        CZ_ZoneServerAuctionSellQuery = 138,
        CZ_ZoneServerAutoSortItem = 219,
        CZ_ZoneServerBFListQuery = 162,
        CZ_ZoneServerBFTeamJoinAnswer = 163,
        CZ_ZoneServerBagDueDate = 115,
        CZ_ZoneServerBattleStatusLog = 258,
        CZ_ZoneServerBattlefieldJoin = 159,
        CZ_ZoneServerBattlefieldLeave = 161,
        CZ_ZoneServerBeastsTowerOP = 234,
        CZ_ZoneServerBlockMailOP = 261,
        CZ_ZoneServerBuyBackOpen = 180,
        CZ_ZoneServerBuyItems = 50,
        CZ_ZoneServerBuySpell = 79,
        CZ_ZoneServerChairCombineCheck = 237,
        CZ_ZoneServerChairCombineCloseUI = 239,
        CZ_ZoneServerChairCombineData = 238,
        CZ_ZoneServerChangeUpanishads = 220,
        CZ_ZoneServerChannelMsg = 58,
        CZ_ZoneServerCheckNodeExit = 43,
        CZ_ZoneServerCheckUpdateLottery = 169,
        CZ_ZoneServerClientCrash = 210,
        CZ_ZoneServerCloseMissionBrief = 70,
        CZ_ZoneServerCoRideInvite = 188,
        CZ_ZoneServerCoSitChairInvite = 236,
        CZ_ZoneServerDailyAwardOP = 221,
        CZ_ZoneServerDivideItem = 110,
        CZ_ZoneServerDropItem = 34,
        CZ_ZoneServerDuelRequest = 149,
        CZ_ZoneServerDuelRequestAnswer = 150,
        CZ_ZoneServerEcho = 83,
        CZ_ZoneServerElfBattleOperate = 194,
        CZ_ZoneServerElfBoxingPlay = 184,
        CZ_ZoneServerElfBoxingUpdateSchedule = 182,
        CZ_ZoneServerElfBoxingUpdateState = 183,
        CZ_ZoneServerElfCheckData = 134,
        CZ_ZoneServerElfGames = 14,
        CZ_ZoneServerElfRacingOP = 230,
        CZ_ZoneServerElfReturn = 131,
        CZ_ZoneServerElfSceneFurnitureUpdate = 259,
        CZ_ZoneServerElfSpellOP = 214,
        CZ_ZoneServerElfStoneUpdate = 128,
        CZ_ZoneServerElfStoneUse = 129,
        CZ_ZoneServerElfTalk = 151,
        CZ_ZoneServerElfTempleChallengeNotify = 262,
        CZ_ZoneServerElfWork = 130,
        CZ_ZoneServerElfWorkResultOK = 133,
        CZ_ZoneServerElftabletComboActive = 250,
        CZ_ZoneServerElftabletSacrifice = 249,
        CZ_ZoneServerEnchantCancel = 111,
        CZ_ZoneServerEnchantUpdate = 46,
        CZ_ZoneServerEnterBattlefieldAnswer = 160,
        CZ_ZoneServerEnterLimitNode = 253,
        CZ_ZoneServerEnterNodeElfContainer = 135,
        CZ_ZoneServerEnterNodeElfInfo = 132,
        CZ_ZoneServerEnterNodeElfInventory = 206,
        CZ_ZoneServerEnterNodeElftablet = 248,
        CZ_ZoneServerEnterNodeEquipAndSpell = 52,
        CZ_ZoneServerEnterNodeInventory = 53,
        CZ_ZoneServerEnterNodeMiniGameData = 105,
        CZ_ZoneServerEnterNodePlayerData = 54,
        CZ_ZoneServerEnterNodeShortcut = 80,
        CZ_ZoneServerEquipTrainSetItem = 203,
        CZ_ZoneServerExchangeItemPin = 91,
        CZ_ZoneServerFamilyBattleQuit = 28,
        CZ_ZoneServerFamilyBattleSchedule = 24,
        CZ_ZoneServerFamilyBattleScheduleExit = 25,
        CZ_ZoneServerFamilyCreate = 76,
        CZ_ZoneServerFamilyDonateMoney = 64,
        CZ_ZoneServerFamilyFarmOp = 196,
        CZ_ZoneServerFamilyFlag = 15,
        CZ_ZoneServerFamilyStatue = 9,
        CZ_ZoneServerFamilyStorageGetItem = 21,
        CZ_ZoneServerFamilyStoragePutItem = 22,
        CZ_ZoneServerFamilyUnionInvite = 26,
        CZ_ZoneServerFamilyUnionInviteResult = 27,
        CZ_ZoneServerFamilyUseSpell = 2,
        CZ_ZoneServerFamilyWishing = 245,
        CZ_ZoneServerFightKingCommand = 215,
        CZ_ZoneServerFishOP = 198,
        CZ_ZoneServerGetCharacterSetting = 247,
        CZ_ZoneServerGetCollection = 4,
        CZ_ZoneServerGetSelectLifeTarget = 148,
        CZ_ZoneServerGetShortcutOfPage = 82,
        CZ_ZoneServerGetStorageData = 87,
        CZ_ZoneServerGiveUpMission = 78,
        CZ_ZoneServerGotoFamilyTreeInstance = 227,
        CZ_ZoneServerHello = 178,
        CZ_ZoneServerHelloOP = 228,
        CZ_ZoneServerIdentifyItem = 90,
        CZ_ZoneServerInlayItem = 92,
        CZ_ZoneServerIsleOP = 197,
        CZ_ZoneServerItemExchangeOP = 235,
        CZ_ZoneServerItemLockCheck = 8,
        CZ_ZoneServerItemMallReceivableEnter = 95,
        CZ_ZoneServerItemMallUseItem = 109,
        CZ_ZoneServerItemUse = 47,
        CZ_ZoneServerJoinGladiator = 212,
        CZ_ZoneServerKusoCombine = 202,
        CZ_ZoneServerLeaveFamilyStorage = 23,
        CZ_ZoneServerLeaveShop = 88,
        CZ_ZoneServerLogoutReq = 84,
        CZ_ZoneServerLookDetailAttr = 158,
        CZ_ZoneServerLookEquip = 157,
        CZ_ZoneServerLotteryGoGetItem = 205,
        CZ_ZoneServerLotteryGoPlay = 204,
        CZ_ZoneServerLoveChallengeOP = 241,
        CZ_ZoneServerLoverBreak = 13,
        CZ_ZoneServerLoverInvite = 10,
        CZ_ZoneServerLoverMarryAnswer = 207,
        CZ_ZoneServerLoverMessage = 11,
        CZ_ZoneServerLuckyBarChoseElf = 172,
        CZ_ZoneServerLuckyBarPlay = 173,
        CZ_ZoneServerLuckyBarPlayRunEnd = 175,
        CZ_ZoneServerLuckyBarPlayerGetMoney = 201,
        CZ_ZoneServerLuckyBarUpdateStatus = 176,
        CZ_ZoneServerLuckyStarChose = 170,
        CZ_ZoneServerLuckyStarQuery = 171,
        CZ_ZoneServerMailDelete = 124,
        CZ_ZoneServerMailGetGold = 126,
        CZ_ZoneServerMailGetItem = 125,
        CZ_ZoneServerMailQuery = 122,
        CZ_ZoneServerMailRead = 123,
        CZ_ZoneServerMailReturn = 127,
        CZ_ZoneServerMailSend = 7,
        CZ_ZoneServerMeleeAttack = 33,
        CZ_ZoneServerMentorshipOP = 229,
        CZ_ZoneServerMessageDelete = 155,
        CZ_ZoneServerMessageExit = 156,
        CZ_ZoneServerMessageListQuery = 152,
        CZ_ZoneServerMessageRead = 154,
        CZ_ZoneServerMessageWrite = 153,
        CZ_ZoneServerMigrationDone = 32,
        CZ_ZoneServerMiniGameStartPlay = 200,
        CZ_ZoneServerMiniGameStopPlay = 174,
        CZ_ZoneServerMissionGoto = 166,
        CZ_ZoneServerMissionListOp = 113,
        CZ_ZoneServerMoveSelf = 30,
        CZ_ZoneServerNodeGroupReset = 181,
        CZ_ZoneServerOpenStarAvenueUI = 226,
        CZ_ZoneServerOpenUIModifyOP = 143,
        CZ_ZoneServerPKPalaceOP = 199,
        CZ_ZoneServerPing = 177,
        CZ_ZoneServerPlayerAction = 42,
        CZ_ZoneServerPlayerEmotion = 49,
        CZ_ZoneServerPlayerPrestigeExchange = 260,
        CZ_ZoneServerQueryAppellation = 121,
        CZ_ZoneServerQueryBattlefieldData = 65,
        CZ_ZoneServerQueryCollection = 5,
        CZ_ZoneServerQueryEnterTimesUpdate = 254,
        CZ_ZoneServerQueryGladiatorCount = 213,
        CZ_ZoneServerQueryLoverInfo = 12,
        CZ_ZoneServerQueryMissionStates = 77,
        CZ_ZoneServerQueryPKPalaceRankInfo = 263,
        CZ_ZoneServerQueryRecommendedEvents = 187,
        CZ_ZoneServerRaceOP = 216,
        CZ_ZoneServerRaceRankInfoQuery = 217,
        CZ_ZoneServerRainbowRoadGameNotify = 243,
        CZ_ZoneServerRainbowRoadTeamNotify = 242,
        CZ_ZoneServerRankInfoQuery = 168,
        CZ_ZoneServerRebirth = 232,
        CZ_ZoneServerReceiveTicket = 29,
        CZ_ZoneServerRepairEquipment = 73,
        CZ_ZoneServerRepairOneItem = 75,
        CZ_ZoneServerReplyDialog = 39,
        CZ_ZoneServerReportProcessInfos = 93,
        CZ_ZoneServerResurrect = 71,
        CZ_ZoneServerRevive = 48,
        CZ_ZoneServerRideCombineCheck = 225,
        CZ_ZoneServerRideCombineCloseUI = 224,
        CZ_ZoneServerRideCombineData = 222,
        CZ_ZoneServerRideTrainInfo = 211,
        CZ_ZoneServerRollTreasureReturn = 189,
        CZ_ZoneServerSBFInviteInfo = 192,
        CZ_ZoneServerSBFOp = 193,
        CZ_ZoneServerSafeQuitCancel = 56,
        CZ_ZoneServerSafeQuitCountDownOver = 57,
        CZ_ZoneServerSafeQuitReq = 55,
        CZ_ZoneServerSaveCollection = 3,
        CZ_ZoneServerSceneEventStateOP = 233,
        CZ_ZoneServerSearchCondition = 0,
        CZ_ZoneServerSearchOpt = 1,
        CZ_ZoneServerSearchTeam = 186,
        CZ_ZoneServerSellItems = 51,
        CZ_ZoneServerSendMotionDataErrorLog = 256,
        CZ_ZoneServerSetAAPoint = 164,
        CZ_ZoneServerSetAARate = 165,
        CZ_ZoneServerSetCarvingStyle = 252,
        CZ_ZoneServerSetChairCombineEquip = 240,
        CZ_ZoneServerSetCollectionPointAbility = 209,
        CZ_ZoneServerSetCrystalComboEquip = 244,
        CZ_ZoneServerSetFamilyEmblem = 108,
        CZ_ZoneServerSetPVP = 16,
        CZ_ZoneServerSetRideCombineEquip = 223,
        CZ_ZoneServerSetSpellStone = 144,
        CZ_ZoneServerSloganUpdate = 98,
        CZ_ZoneServerSpellBreak = 41,
        CZ_ZoneServerSpellCastToLife = 37,
        CZ_ZoneServerSpellCastToLocation = 44,
        CZ_ZoneServerSpellCastToNearby = 85,
        CZ_ZoneServerSpellCastToNowhere = 45,
        CZ_ZoneServerSpellStorageOP = 231,
        CZ_ZoneServerStateCancel = 145,
        CZ_ZoneServerStorageDeposit = 86,
        CZ_ZoneServerStorageExpand = 94,
        CZ_ZoneServerStrengthenClose = 142,
        CZ_ZoneServerStrengthenItem = 141,
        CZ_ZoneServerSwitchItemLocation = 35,
        CZ_ZoneServerTalkToNPC = 38,
        CZ_ZoneServerTargetUpdate = 146,
        CZ_ZoneServerTeamChangeLeader = 116,
        CZ_ZoneServerTeamInvite = 18,
        CZ_ZoneServerTeamInviteAnswer = 19,
        CZ_ZoneServerTeamInviteCancel = 20,
        CZ_ZoneServerTeamLeave = 17,
        CZ_ZoneServerTeamOperation = 104,
        CZ_ZoneServerTeamRadarAttention = 112,
        CZ_ZoneServerTeamRecruitMsg = 185,
        CZ_ZoneServerTerritoryJoin = 190,
        CZ_ZoneServerTerritoryQuery = 191,
        CZ_ZoneServerTextCommand = 31,
        CZ_ZoneServerTradeAddItem = 62,
        CZ_ZoneServerTradeCancel = 69,
        CZ_ZoneServerTradeConfirm = 68,
        CZ_ZoneServerTradeModifyGold = 67,
        CZ_ZoneServerTradeReady = 117,
        CZ_ZoneServerTradeRemoveItem = 66,
        CZ_ZoneServerTradeRequest = 60,
        CZ_ZoneServerTradeRequestAccept = 61,
        CZ_ZoneServerTradeReset = 179,
        CZ_ZoneServerTradeUnConfirm = 118,
        CZ_ZoneServerTransport = 114,
        CZ_ZoneServerTransportToPoint = 208,
        CZ_ZoneServerTreasurePickup = 59,
        CZ_ZoneServerTurnSelf = 147,
        CZ_ZoneServerUpdateAppellation = 119,
        CZ_ZoneServerUpdateAppellationTop = 120,
        CZ_ZoneServerUpdateArenaScore = 195,
        CZ_ZoneServerUpdateBotData = 167,
        CZ_ZoneServerUpdateElfPickSetting = 246,
        CZ_ZoneServerUpdateEquipment = 36,
        CZ_ZoneServerUpdateFamily = 107,
        CZ_ZoneServerUpdateOptionSettings = 251,
        CZ_ZoneServerUpdateShortcut = 81,
        CZ_ZoneServerUseArenaPoint = 218,
        CZ_ZoneServerUseMoneyResetSpellAA = 257,
        CZ_ZoneServerUseSkillPoint = 40,
        CZ_ZoneServerVendorBuy = 101,
        CZ_ZoneServerVendorClose = 99,
        CZ_ZoneServerVendorCloseVending = 103,
        CZ_ZoneServerVendorCloseView = 100,
        CZ_ZoneServerVendorSellItem = 102,
        CZ_ZoneServerVendorUseItem = 106,
        CZ_ZoneServerVictoryDeclaration = 6,
        CZ_ZoneServerWhoIs = 63
    }

    // GMTool <-> ZoneServer
    public enum CG_Commands : ushort {
        CG_ServerTextCommand = 0,
        CG_ServerLogin = 1,
        CG_ClientCharacterList = 2,
        CG_ClientCharacter = 3,
        CG_ClientTextOutput = 4,
        CG_ClientChannel = 5,
        CG_ClientCharLocate = 6
    }

    public const ushort CG_ClientDataTest = 0;
    public const ushort CG_ClientGetContainerItem = 0;
    public const ushort CG_ClientGetMail = 0;
    public const ushort CG_ClientGetMissionState = 0;
    public const ushort CG_ClientGetMoney = 0;
    public const ushort DBA_AgentDBACommand = 20;
    public const ushort DBA_ClientAddFamilyMember = 31;
    public const ushort DBA_ClientAllFamily = 26;
    public const ushort DBA_ClientAllLover = 39;
    public const ushort DBA_ClientAllTerritory = 40;
    public const ushort DBA_ClientChangeFamily = 28;
    public const ushort DBA_ClientChannelMsg = 33;
    public const ushort DBA_ClientCollection = 37;
    public const ushort DBA_ClientContainer = 21;
    public const ushort DBA_ClientDelPlayerOK = 25;
    public const ushort DBA_ClientElfData = 34;
    public const ushort DBA_ClientEnchant = 22;
    public const ushort DBA_ClientFamilyAllMember = 30;
    public const ushort DBA_ClientFamilyAllMessage = 38;
    public const ushort DBA_ClientFamilyCropInfo = 46;
    public const ushort DBA_ClientFamilyStorage = 41;
    public const ushort DBA_ClientFinishPlayerData = 36;
    public const ushort DBA_ClientMentorship = 48;
    public const ushort DBA_ClientMigrationCharacter = 32;
    public const ushort DBA_ClientNewFamily = 27;
    public const ushort DBA_ClientNodeID = 23;
    public const ushort DBA_ClientPlayerData = 24;
    public const ushort DBA_ClientRaceTeamInfo = 47;
    public const ushort DBA_ClientRecommendedEvents = 44;
    public const ushort DBA_ClientRemoveFamily = 29;
    public const ushort DBA_ClientShortcut = 35;
    public const ushort DBA_ClientSpellMaster = 42;
    public const ushort DBA_ClientTransportData = 43;
    public const ushort DBA_ReloadTranslate = 45;
    public const ushort MW_MissionServerTextExCmd = 14;
    public const ushort MW_MissionServerTextExCmdRemoteWorld = 15;
    public const ushort MW_MissionServerTextExCmdRemoteZone = 16;
    public const ushort MW_WorldServerCheckFamilyInvite = 7;
    public const ushort MW_WorldServerCrossZone = 3;
    public const ushort MW_WorldServerFBMsgUpdate = 9;
    public const ushort MW_WorldServerFunctionSwitchUpdate = 13;
    public const ushort MW_WorldServerItemMallMailCheckOK = 2;
    public const ushort MW_WorldServerItemMallMailSendResult = 1;
    public const ushort MW_WorldServerTell = 0;
    public const ushort MW_WorldServerTextExCmd = 10;
    public const ushort MW_WorldServerTextExCmdRemoteWorld = 11;
    public const ushort MW_WorldServerTextExCmdRemoteZone = 12;
    public const ushort MW_WorldServerUpdateBlackList = 4;
    public const ushort MW_WorldServerUpdateFriendMember = 6;
    public const ushort MW_WorldServerUpdatePrestigeData = 5;
    public const ushort MW_WorldTextCommand = 19;
    public const ushort T_ClientGetTicket = 2;
    public const ushort T_ClientUseTicket = 3;
    public const ushort T_ServerGetTicket = 0;
    public const ushort T_ServerUseTicket = 1;
    public const ushort ZM_MonsterServerListRebornMonster = 148;
    public const ushort ZM_MonsterServerModifyRebornMonster = 150;
    public const ushort ZM_MonsterServerMonsterDieReport = 147;
    public const ushort ZM_MonsterServerMonsterReport = 146;
    public const ushort ZM_MonsterServerRegenerationReport = 156;
    public const ushort ZM_MonsterServerRemoveNode = 153;
    public const ushort ZM_MonsterServerRemoveRebornMonster = 151;
    public const ushort ZM_MonsterServerSetRebornMonster = 149;
    public const ushort ZM_MonsterServerStartCharRegenerate = 154;
    public const ushort ZM_MonsterServerStopCharRegenerate = 155;
    public const ushort ZM_MonsterServerUnRegRebornMonster = 152;
    public const ushort ZM_ZoneServerAddIsleRecord = 127;
    public const ushort ZM_ZoneServerCharRegenerate = 67;
    public const ushort ZM_ZoneServerCropInfos = 130;
    public const ushort ZM_ZoneServerFamilyFarmHireds = 126;
    public const ushort ZM_ZoneServerIsleDBA = 124;
    public const ushort ZM_ZoneServerIsleFishGrounds = 128;
    public const ushort ZM_ZoneServerMessageToCharacter = 66;
    public const ushort ZM_ZoneServerRebornMonster = 64;
    public const ushort ZM_ZoneServerReportMonster = 63;
    public const ushort ZM_ZoneServerSetRebornMonsterResult = 65;
    public const ushort ZM_ZoneServerUpdateIsle = 125;
    public const ushort ZM_ZoneServerUpdateIsleFishGround = 129;
    public const ushort ZM_ZoneServerUpdatePKList = 17;
    public const ushort ZMis_MissionServerAccountSharedOP = 189;
    public const ushort ZMis_MissionServerAddFamilyMessage = 54;
    public const ushort ZMis_MissionServerAddIsleRecord = 182;
    public const ushort ZMis_MissionServerAuctionBuyQuery = 191;
    public const ushort ZMis_MissionServerBattlefieldClose = 171;
    public const ushort ZMis_MissionServerBattlefieldEraseMember = 170;
    public const ushort ZMis_MissionServerBattlefieldJoin = 169;
    public const ushort ZMis_MissionServerBattlefieldList = 172;
    public const ushort ZMis_MissionServerBattlefieldTeamJoinAnswer = 175;
    public const ushort ZMis_MissionServerBattlefieldUpdateStatus = 174;
    public const ushort ZMis_MissionServerBeastsTowerOP = 187;
    public const ushort ZMis_MissionServerBlockMailOP = 190;
    public const ushort ZMis_MissionServerChannelMsg = 176;
    public const ushort ZMis_MissionServerCheckFamilyInvite = 8;
    public const ushort ZMis_MissionServerCloseMissionBrief = 158;
    public const ushort ZMis_MissionServerCrossZone = 166;
    public const ushort ZMis_MissionServerCrossZoneRequest = 165;
    public const ushort ZMis_MissionServerDelayMessage = 186;
    public const ushort ZMis_MissionServerEnterBattlefieldAnswer = 173;
    public const ushort ZMis_MissionServerFamilyBattleDataUpdate = 168;
    public const ushort ZMis_MissionServerFamilyBattleResult = 167;
    public const ushort ZMis_MissionServerFightKingCommand = 184;
    public const ushort ZMis_MissionServerGiveUpMission = 160;
    public const ushort ZMis_MissionServerIDReport = 56;
    public const ushort ZMis_MissionServerIsleOP = 181;
    public const ushort ZMis_MissionServerItemExchange = 188;
    public const ushort ZMis_MissionServerItemMallMailCheck = 53;
    public const ushort ZMis_MissionServerItemMallMailSend = 52;
    public const ushort ZMis_MissionServerListDialogue = 142;
    public const ushort ZMis_MissionServerLuckyStarBet = 145;
    public const ushort ZMis_MissionServerMailSend = 162;
    public const ushort ZMis_MissionServerMessageWrite = 164;
    public const ushort ZMis_MissionServerMigrationDone = 159;
    public const ushort ZMis_MissionServerMobDieReport = 161;
    public const ushort ZMis_MissionServerNodeCreate = 57;
    public const ushort ZMis_MissionServerOnDialogueSelected = 143;
    public const ushort ZMis_MissionServerQueryLuckyStar = 144;
    public const ushort ZMis_MissionServerRaceResult = 185;
    public const ushort ZMis_MissionServerRefreshRecommendedEvents = 49;
    public const ushort ZMis_MissionServerRemoteClient = 177;
    public const ushort ZMis_MissionServerRemovePMS = 157;
    public const ushort ZMis_MissionServerSendSystemMail = 163;
    public const ushort ZMis_MissionServerTextExCmd = 178;
    public const ushort ZMis_MissionServerTextExCmdRemoteWorld = 179;
    public const ushort ZMis_MissionServerTextExCmdRemoteZone = 180;
    public const ushort ZMis_MissionServerUpdateElfSchoolScore = 183;
    public const ushort ZMis_MissionServerUpdatePKList = 18;
    public const ushort ZMis_MissionServerUpdateRecommendedEvents = 50;
    public const ushort ZMis_ZoneServerAccountSharedUpdate = 139;
    public const ushort ZMis_ZoneServerAchievementUpdate = 92;
    public const ushort ZMis_ZoneServerAuctionBuyList = 81;
    public const ushort ZMis_ZoneServerAuctionBuyOK = 82;
    public const ushort ZMis_ZoneServerAuctionCancelOK = 83;
    public const ushort ZMis_ZoneServerAuctionSellList = 84;
    public const ushort ZMis_ZoneServerAuctionSellResult = 85;
    public const ushort ZMis_ZoneServerBattlefieldChangeCharNum = 108;
    public const ushort ZMis_ZoneServerBattlefieldEraseMember = 104;
    public const ushort ZMis_ZoneServerBattlefieldJoinResult = 100;
    public const ushort ZMis_ZoneServerBattlefieldList = 103;
    public const ushort ZMis_ZoneServerBattlefieldSetup = 107;
    public const ushort ZMis_ZoneServerBattlefieldTeamJoin = 105;
    public const ushort ZMis_ZoneServerBeastsTowerUpdate = 137;
    public const ushort ZMis_ZoneServerBroadCastElfSchoolFinalResult = 134;
    public const ushort ZMis_ZoneServerBuyBackGetItem = 112;
    public const ushort ZMis_ZoneServerBuyBackList = 111;
    public const ushort ZMis_ZoneServerBuybackInitAllocate = 120;
    public const ushort ZMis_ZoneServerCharNotQuit = 91;
    public const ushort ZMis_ZoneServerCrossZoneResult = 93;
    public const ushort ZMis_ZoneServerDeallocateItemID = 113;
    public const ushort ZMis_ZoneServerDropItem = 77;
    public const ushort ZMis_ZoneServerEnterBattlefield = 101;
    public const ushort ZMis_ZoneServerEnterBattlefieldAnswer = 106;
    public const ushort ZMis_ZoneServerFamilyBattleInfo = 97;
    public const ushort ZMis_ZoneServerFamilyBattleSchedule = 98;
    public const ushort ZMis_ZoneServerFamilyStorageLog = 96;
    public const ushort ZMis_ZoneServerFamilyStorageUpdate = 95;
    public const ushort ZMis_ZoneServerFamilyUnionInvite = 99;
    public const ushort ZMis_ZoneServerFightKingCommand = 131;
    public const ushort ZMis_ZoneServerFunctionSwitchUpdate = 140;
    public const ushort ZMis_ZoneServerGMToolGetInfo = 192;
    public const ushort ZMis_ZoneServerGMToolGetMail = 194;
    public const ushort ZMis_ZoneServerGMToolGetMission = 193;
    public const ushort ZMis_ZoneServerItemExchangeUpdate = 138;
    public const ushort ZMis_ZoneServerListDialogue = 58;
    public const ushort ZMis_ZoneServerLoverUpdate = 94;
    public const ushort ZMis_ZoneServerLuckyStarBet = 110;
    public const ushort ZMis_ZoneServerMailDeleteResult = 73;
    public const ushort ZMis_ZoneServerMailGetGoldOK = 79;
    public const ushort ZMis_ZoneServerMailGetItemOK = 78;
    public const ushort ZMis_ZoneServerMailList = 71;
    public const ushort ZMis_ZoneServerMailRead = 72;
    public const ushort ZMis_ZoneServerMailReceive = 75;
    public const ushort ZMis_ZoneServerMailReturnResult = 80;
    public const ushort ZMis_ZoneServerMailSendResult = 74;
    public const ushort ZMis_ZoneServerMessageDeleteResult = 90;
    public const ushort ZMis_ZoneServerMessageList = 87;
    public const ushort ZMis_ZoneServerMessageRead = 89;
    public const ushort ZMis_ZoneServerMessageWriteResult = 88;
    public const ushort ZMis_ZoneServerNPCTalkCheck = 118;
    public const ushort ZMis_ZoneServerPutItem = 76;
    public const ushort ZMis_ZoneServerQueryLuckyStar = 62;
    public const ushort ZMis_ZoneServerRaceRankInfo = 133;
    public const ushort ZMis_ZoneServerRankAwardTestResult = 195;
    public const ushort ZMis_ZoneServerRankInfo = 109;
    public const ushort ZMis_ZoneServerRefreshTerritoryNodeEnchant = 141;
    public const ushort ZMis_ZoneServerRefreshTreeEnchant = 135;
    public const ushort ZMis_ZoneServerRemoteClient = 114;
    public const ushort ZMis_ZoneServerReplyDialogue = 59;
    public const ushort ZMis_ZoneServerReportID = 55;
    public const ushort ZMis_ZoneServerSearchInfo = 86;
    public const ushort ZMis_ZoneServerShowSceneEventState = 136;
    public const ushort ZMis_ZoneServerStartBattlefield = 102;
    public const ushort ZMis_ZoneServerTerritoryInfo = 121;
    public const ushort ZMis_ZoneServerTerritoryJoin = 123;
    public const ushort ZMis_ZoneServerTerritoryQuery = 122;
    public const ushort ZMis_ZoneServerTextExCmd = 115;
    public const ushort ZMis_ZoneServerTextExCmdRemoteWorld = 117;
    public const ushort ZMis_ZoneServerTextExCmdRemoteZone = 116;
    public const ushort ZMis_ZoneServerTextOutput = 61;
    public const ushort ZMis_ZoneServerTextOutputIndex = 69;
    public const ushort ZMis_ZoneServerTransitionCommands = 60;
    public const ushort ZMis_ZoneServerUpdateMissionState = 70;
    public const ushort ZMis_ZoneServerUpdateNPCSymbols = 68;
    public const ushort ZMis_ZoneServerUpdatePrestigeData = 119;
    public const ushort ZMis_ZoneServerUpdateRaceTeam = 132;
    public const ushort ZMis_ZoneServerUpdateRecommendedEvents = 51;
    public const ushort ZW_WorldServerAllUsers = 2;
    public const ushort ZW_WorldServerChannelMsg = 8;
    public const ushort ZW_WorldServerCharacterArrived = 4;
    public const ushort ZW_WorldServerFBMsgUpdate = 14;
    public const ushort ZW_WorldServerFamilyCreation = 9;
    public const ushort ZW_WorldServerGetCloneItemID = 13;
    public const ushort ZW_WorldServerIDReport = 0;
    public const ushort ZW_WorldServerItemMallReceieveAttempt = 12;
    public const ushort ZW_WorldServerLogout = 10;
    public const ushort ZW_WorldServerNotifyEntry = 3;
    public const ushort ZW_WorldServerResetTime = 5;
    public const ushort ZW_WorldServerReturnToCharacterList = 6;
    public const ushort ZW_WorldServerTeamLeavedNotify = 7;
    public const ushort ZW_WorldServerTell = 1;
    public const ushort ZW_WorldServerTextCommand = 11;
    public const ushort ZW_WorldServerTextExCmd = 15;
    public const ushort ZW_ZoneServerChangeFamily = 21;
    public const ushort ZW_ZoneServerChannelMsg = 20;
    public const ushort ZW_ZoneServerCharacterArrive = 18;
    public const ushort ZW_ZoneServerCharacterArrivedDest = 19;
    public const ushort ZW_ZoneServerDestShutdown = 17;
    public const ushort ZW_ZoneServerFamilyUseSpell = 28;
    public const ushort ZW_ZoneServerGMToolGetInfo = 31;
    public const ushort ZW_ZoneServerGetCloneItemID = 26;
    public const ushort ZW_ZoneServerItemMallReceieveAttempt = 25;
    public const ushort ZW_ZoneServerNewFamily = 22;
    public const ushort ZW_ZoneServerRemoveFamily = 23;
    public const ushort ZW_ZoneServerReportID = 16;
    public const ushort ZW_ZoneServerTextCommand = 24;
    public const ushort ZW_ZoneServerTextExCmd = 30;
    public const ushort ZW_ZoneServerUpdateFortuneBag = 27;
    public const ushort ZW_ZoneServerUpdateLottery = 29;
}
